import SwiftUI
import Speech
import AVFoundation
import PhotosUI
import UIKit

private enum AppTheme {
    static let background = LinearGradient(colors: [Color(red: 0.91, green: 0.96, blue: 1), .white, Color(red: 0.94, green: 0.97, blue: 1)], startPoint: .topLeading, endPoint: .bottomTrailing)
    static let surface = Color.white.opacity(0.78), surfaceAlt = Color.white.opacity(0.62), primary = Color(red: 0.04, green: 0.15, blue: 0.34)
    static let ledgerAccent = Color.blue, todoAccent = Color.green, memoAccent = Color.orange, ideaAccent = Color.purple
    static let cornerRadius: CGFloat = 24, shadow = Color.blue.opacity(0.1), spacing: CGFloat = 14
}
private let appBackground = AppTheme.background
private enum AppFocus: Hashable { case homeInput, searchInput, raw, tags, merchant, amount, currency, category, payment, location }

private struct LakeBackground: View {
    var body: some View { ZStack { appBackground; Circle().fill(.cyan.opacity(0.16)).frame(width: 360).blur(radius: 75).offset(x: 170, y: -260); Circle().fill(.orange.opacity(0.1)).frame(width: 250).blur(radius: 65).offset(x: -150, y: -170); Image(systemName: "mountain.2.fill").resizable().scaledToFit().frame(width: 520).foregroundStyle(LinearGradient(colors: [.blue.opacity(0.13), .cyan.opacity(0.025)], startPoint: .top, endPoint: .bottom)).offset(y: -95); Rectangle().fill(.white.opacity(0.28)).frame(height: 210).blur(radius: 24).offset(y: 90) }.ignoresSafeArea() }
}

final class IdentitySession: IdentityGate, ObservableObject, @unchecked Sendable {
    @Published var confirmedUserID: String? { didSet { UserDefaults.standard.set(confirmedUserID, forKey: "confirmedUserID") } }
    init() { confirmedUserID = UserDefaults.standard.string(forKey: "confirmedUserID") }
    func confirm() { confirmedUserID = "local-\(UUID().uuidString)" }
}

@MainActor final class AppModel: ObservableObject {
    @Published var records: [Record] = []; @Published var error: String?
    let identity = IdentitySession(); let core: QuickNoteCore; let parser = DeterministicDraftParser()
    init() { let folder = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]; core = QuickNoteCore(store: FileRecordStore(url: folder.appendingPathComponent("records.json")), identity: identity); reload() }
    func reload() { do { records = try core.records() } catch { self.error = error.localizedDescription } }
    func save(_ value: Record) throws { _ = try core.save(value); reload() }
}

@main struct AIQuickNoteApp: App { @StateObject private var model = AppModel(); var body: some Scene { WindowGroup { RootView().environmentObject(model) } } }

struct RootView: View {
    @EnvironmentObject private var model: AppModel
    var body: some View { NavigationStack { HomeView() }.tint(.indigo).alert("操作失败", isPresented: Binding(get: { model.error != nil }, set: { if !$0 { model.error = nil } })) { Button("确定") {} } message: { Text(model.error ?? "未知错误") } }
}

struct HomeView: View {
    @EnvironmentObject private var model: AppModel; @StateObject private var speech = SpeechInput()
    @State private var text = ""; @State private var draft: Record?; @State private var query: RecordQuery?; @State private var attachmentMenu = false; @State private var photos = false; @State private var camera = false; @State private var photo: PhotosPickerItem?; @FocusState private var focused: AppFocus?
    var body: some View {
        ScrollView { VStack(alignment: .leading, spacing: 12) { ZStack(alignment: .topTrailing) { VStack(alignment: .leading, spacing: 6) { Text("AI 随手记").font(.system(size: 38, weight: .bold)).foregroundStyle(AppTheme.primary); Text("记录生活，交给 AI 处理 ✨").font(.title3).foregroundStyle(.blue.opacity(0.68)); Spacer().frame(height: 12); Text(Date.now.formatted(.dateTime.month().day().weekday(.wide))).font(.headline).foregroundStyle(AppTheme.primary); Text("今天也值得被好好记录 ☀️").foregroundStyle(.blue.opacity(0.62)) }.frame(maxWidth: .infinity, alignment: .leading); VStack(alignment: .trailing, spacing: 12) { Image(systemName: "person.fill").font(.title2).foregroundStyle(.blue.opacity(0.65)).frame(width: 54, height: 54).background(.ultraThinMaterial, in: Circle()).overlay(Circle().stroke(.white.opacity(0.9))); Text("让每一个\n平凡的瞬间\n都有意义。").font(.callout.italic()).multilineTextAlignment(.trailing).foregroundStyle(.indigo.opacity(0.72)).rotationEffect(.degrees(-5)) } }.padding(.horizontal, 4); LazyVGrid(columns: [.init(.flexible()), .init(.flexible())], spacing: 14) { ForEach(Module.allCases) { module in NavigationLink(value: module) { ModuleCard(module: module, records: model.records.filter { $0.module == module }) }.simultaneousGesture(TapGesture().onEnded { focused = nil }) } } }.padding(.horizontal, 16).padding(.top, 8).padding(.bottom, 10).background(Color.clear.contentShape(Rectangle()).onTapGesture { focused = nil }) }.scrollDismissesKeyboard(.interactively)
            .background(LakeBackground()).safeAreaInset(edge: .bottom) { captureBar }.toolbar(.hidden, for: .navigationBar)
            .navigationDestination(for: Module.self) { ModuleListView(module: $0) }.navigationDestination(item: $draft) { ReviewView(draft: $0) { text = "" } }
            .navigationDestination(isPresented: Binding(get: { query != nil }, set: { if !$0 { query = nil } })) { SearchView(initialQuery: query ?? RecordQuery()) }
            .confirmationDialog("添加图片", isPresented: $attachmentMenu) { Button("拍照") { if UIImagePickerController.isSourceTypeAvailable(.camera) { camera = true } else { model.error = "当前设备没有可用相机。" } }; Button("从相册选择") { photos = true }; Button("取消", role: .cancel) {} }
            .photosPicker(isPresented: $photos, selection: $photo, matching: .images).sheet(isPresented: $camera) { CameraPicker() }
            .onAppear { model.reload(); focused = nil }.onDisappear { focused = nil; speech.stop() }
            .onChange(of: speech.transcript) { text = $0 }.onChange(of: speech.finishedTranscript) { if $0 != nil { submit() } }.onChange(of: speech.error) { if let value = $0 { model.error = value } }
    }
    private var captureBar: some View { HStack(spacing: 12) {
        Button { focused = nil; speech.isRecording ? speech.stop() : speech.start() } label: { Image(systemName: speech.isRecording ? "stop.fill" : "mic.fill").font(.system(size: 34, weight: .semibold)).frame(width: 84, height: 84).background(speech.isRecording ? AnyShapeStyle(.red) : AnyShapeStyle(LinearGradient(colors: [.blue.opacity(0.65), .cyan.opacity(0.45)], startPoint: .topLeading, endPoint: .bottomTrailing))).foregroundStyle(.white).clipShape(Circle()).overlay(Circle().stroke(.white.opacity(0.9), lineWidth: 1)).shadow(color: .blue.opacity(0.3), radius: 16, y: 7) }.accessibilityLabel("语音输入")
        HStack(spacing: 8) { TextField("说一句，或输入搜索", text: $text, axis: .vertical).focused($focused, equals: .homeInput).lineLimit(1...3).submitLabel(.search).onSubmit { openSearch() }; Button { openSearch() } label: { Image(systemName: "magnifyingglass").font(.title2).foregroundStyle(.blue.opacity(0.8)) }.accessibilityLabel("搜索") }.padding(.horizontal, 18).frame(minHeight: 70).background(.white.opacity(0.72), in: Capsule()).overlay(Capsule().stroke(.white.opacity(0.9), lineWidth: 1)).shadow(color: .blue.opacity(0.12), radius: 12, y: 5)
        Button { focused = nil; if text.trimmed.isEmpty { attachmentMenu = true } else { submit() } } label: { Image(systemName: text.trimmed.isEmpty ? "plus" : "arrow.up").font(.system(size: 27, weight: .semibold)).frame(width: 64, height: 64).background(.white.opacity(0.8), in: Circle()).overlay(Circle().stroke(.white.opacity(0.9), lineWidth: 1)).shadow(color: .blue.opacity(0.15), radius: 10, y: 4) }.accessibilityLabel(text.trimmed.isEmpty ? "添加图片" : "提交")
    }.padding(.horizontal, 14).padding(.vertical, 12).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 36)).padding(.horizontal, 8).shadow(color: .black.opacity(0.08), radius: 16, y: -3) }
    private func submit() { let input = text.trimmed; guard !input.isEmpty else { return }; focused = nil; speech.stop(); Task { do { switch try await model.parser.parse(input) { case .create(let value): draft = value; case .search(let value): query = value } } catch { draft = Record(module: .memo, rawInput: input); model.error = "解析不可用，已保留原文供手工填写。" } } }
    private func openSearch() { focused = nil; speech.stop(); query = RecordQuery(keyword: text.trimmed) }
}

struct ModuleCard: View { let module: Module; let records: [Record]; var body: some View { ZStack(alignment: .bottomTrailing) { VStack(spacing: 5) { Image(systemName: module.decoration).font(.system(size: 48, weight: .light)); Image(systemName: "leaf.fill").font(.title) }.foregroundStyle(module.color.opacity(0.15)).padding(10); VStack(alignment: .leading, spacing: 7) { HStack { Image(systemName: module.icon).font(.title2).foregroundStyle(module.color).frame(width: 44, height: 44).background(module.color.opacity(0.13), in: RoundedRectangle(cornerRadius: 15)); Spacer(); Image(systemName: "chevron.right").foregroundStyle(AppTheme.primary.opacity(0.55)).frame(width: 32, height: 32).background(.white.opacity(0.66), in: Circle()) }; Text(module.title).font(.title2.bold()).foregroundStyle(AppTheme.primary); Text(module.subtitle).font(.caption).foregroundStyle(.secondary).lineLimit(1); VStack(alignment: .leading, spacing: 3) { ForEach(records.prefix(2)) { Text($0.content).font(.caption).lineLimit(1) }; if records.isEmpty { Text("从一句话开始记录…").font(.caption) } }.foregroundStyle(.blue.opacity(0.62)).padding(8).frame(maxWidth: .infinity, alignment: .leading).background(.white.opacity(0.42), in: RoundedRectangle(cornerRadius: 14)); Spacer(minLength: 0); Text("\(records.count) 条记录").font(.headline).foregroundStyle(module.color) }.frame(maxWidth: .infinity, minHeight: 204, alignment: .leading).padding(14) }.background(LinearGradient(colors: [.white.opacity(0.88), module.color.opacity(0.09)], startPoint: .topLeading, endPoint: .bottomTrailing), in: RoundedRectangle(cornerRadius: 30)).overlay(RoundedRectangle(cornerRadius: 30).stroke(.white.opacity(0.95), lineWidth: 1.2)).shadow(color: module.color.opacity(0.17), radius: 18, y: 9) } }

struct ReviewView: View {
    @EnvironmentObject private var model: AppModel; @Environment(\.dismiss) private var dismiss; @StateObject private var speech = SpeechInput(); @State var draft: Record; @State private var identity = false; @State private var searchQuery: RecordQuery?; @State private var voicePrefix = ""; let onSaved: () -> Void
    var body: some View { RecordForm(record: $draft, showRawInput: true, saveTitle: "确认保存", onSave: save, onSearch: search, onReparse: { reparse() }, onVoice: toggleVoice, isRecording: speech.isRecording, voiceLabel: speech.statusText).navigationTitle("确认记录").navigationBarTitleDisplayMode(.inline).navigationDestination(isPresented: Binding(get: { searchQuery != nil }, set: { if !$0 { searchQuery = nil } })) { SearchView(initialQuery: searchQuery ?? RecordQuery()) }.sheet(isPresented: $identity) { VStack(spacing: 20) { Image(systemName: "person.crop.circle.badge.checkmark").font(.system(size: 56)); Text("首次保存需要确认身份").font(.title2.bold()); Text("仅确认本地数据归属，不会备份、上传或分享。"); Button("确认本机身份并保存") { model.identity.confirm(); identity = false; save(draft) }.buttonStyle(.borderedProminent) }.padding().presentationDetents([.medium]) }.task(id: draft.rawInput) { try? await Task.sleep(for: .milliseconds(400)); guard !Task.isCancelled else { return }; await parseCurrentInput() }.onChange(of: speech.transcript) { let value = $0.trimmed; guard !value.isEmpty else { return }; draft.rawInput = [voicePrefix, value].filter { !$0.isEmpty }.joined(separator: "，") }.onChange(of: speech.error) { if let value = $0 { model.error = value } }.onDisappear { speech.stop() } }
    private func save(_ value: Record) { do { try model.save(value); onSaved(); dismiss() } catch CoreError.identityRequired { identity = true } catch { model.error = error.localizedDescription } }
    private func search(_ value: Record) { draft = value; searchQuery = RecordQuery(keyword: value.merchant ?? value.paymentMethod ?? value.content, modules: [value.module], importantOnly: value.important, tags: value.tags) }
    private func reparse() { Task { await parseCurrentInput() } }
    private func toggleVoice() { if speech.isRecording { speech.stop() } else { voicePrefix = draft.rawInput.trimmed; speech.start() } }
    private func parseCurrentInput() async { let input = draft.rawInput.trimmed; guard !input.isEmpty else { return }; do { if case .create(var value) = try await model.parser.parse(input) { value.id = draft.id; value.ownerID = draft.ownerID; value.createdAt = draft.createdAt; draft = value } } catch { model.error = "重新解析失败，已保留当前内容。" } }
}

struct ModuleListView: View {
    @EnvironmentObject private var model: AppModel; @State private var adding = false; let module: Module
    var body: some View { List(model.records.filter { $0.module == module }) { record in NavigationLink(value: record) { RecordRow(record: record) }.listRowBackground(Color.white.opacity(0.78)) }.listStyle(.insetGrouped).scrollContentBackground(.hidden).scrollDismissesKeyboard(.interactively).background(LakeBackground()).navigationTitle(module.title).toolbar { Button { adding = true } label: { Image(systemName: "plus") } }.sheet(isPresented: $adding) { NavigationStack { ModuleComposerView(module: module) } }.navigationDestination(for: Record.self) { DetailView(record: $0) }.overlay { if model.records.allSatisfy({ $0.module != module }) { ContentUnavailableView("暂无记录", systemImage: module.icon) } }.onAppear { model.reload() } }
}

struct ModuleComposerView: View {
    @Environment(\.dismiss) private var dismiss; @State private var text = ""; @State private var draft: Record?; @FocusState private var focused: Bool; let module: Module
    var body: some View { VStack { TextField("输入一条\(module.title)记录", text: $text, axis: .vertical).focused($focused).submitLabel(.done).onSubmit { focused = false }.textFieldStyle(.roundedBorder).padding(); Button("继续") { focused = false; draft = Record(module: module, rawInput: text) }.buttonStyle(.borderedProminent).disabled(text.trimmed.isEmpty); Spacer() }.background(LakeBackground().onTapGesture { focused = false }).navigationTitle("新建\(module.title)").toolbar { Button("取消") { focused = false; dismiss() } }.navigationDestination(item: $draft) { ReviewView(draft: $0) { dismiss() } } }
}

struct SearchView: View {
    @EnvironmentObject private var model: AppModel; @State private var keyword: String; @State private var modules: Set<Module>; @State private var important: Bool; @State private var results: [Record] = []; @State private var selectedRecord: Record?; @FocusState private var focused: AppFocus?
    private let tags: [String]; private let dateStart: Date?; private let dateEnd: Date?; private let minimumAmount: Decimal?; private let minimumInclusive: Bool; private let maximumAmount: Decimal?; private let maximumInclusive: Bool; private let currency: String?; private let category: String?
    init(initialQuery: RecordQuery) { _keyword = State(initialValue: initialQuery.keyword); _modules = State(initialValue: initialQuery.modules); _important = State(initialValue: initialQuery.importantOnly); tags = initialQuery.tags; dateStart = initialQuery.dateStart; dateEnd = initialQuery.dateEnd; minimumAmount = initialQuery.minimumAmount; minimumInclusive = initialQuery.minimumInclusive; maximumAmount = initialQuery.maximumAmount; maximumInclusive = initialQuery.maximumInclusive; currency = initialQuery.currency; category = initialQuery.category }
    var body: some View { ScrollView { VStack(spacing: 18) { searchCard("自动总额", "sum", .blue) { if totalKeys.isEmpty { Text("—").font(.title.bold()).foregroundStyle(.secondary) } else { LazyVGrid(columns: [.init(.flexible()), .init(.flexible())], spacing: 10) { ForEach(totalKeys, id: \.self) { key in HStack { VStack(alignment: .leading, spacing: 5) { Text(key).font(.caption).foregroundStyle(.secondary); Text(String(describing: totalMap[key] ?? 0)).font(.title2.bold()).foregroundStyle(.blue) }; Spacer(); Image(systemName: "banknote.fill").foregroundStyle(Color.blue.opacity(0.35)) }.padding(14).background(Color.blue.opacity(0.09), in: RoundedRectangle(cornerRadius: 18)) } } } }; searchCard("查询条件", "slider.horizontal.3", .purple) { HStack { Image(systemName: "magnifyingglass").foregroundStyle(.secondary); TextField("关键词", text: $keyword).focused($focused, equals: .searchInput).submitLabel(.search).onSubmit { focused = nil; search() }; if !keyword.isEmpty { Button { keyword = "" } label: { Image(systemName: "xmark.circle.fill").foregroundStyle(.secondary) } } }.padding(15).background(.white.opacity(0.68), in: RoundedRectangle(cornerRadius: 20)); LazyVGrid(columns: [.init(.flexible()), .init(.flexible())], spacing: 9) { ForEach(Module.allCases) { module in Button { if modules.contains(module) { modules.remove(module) } else { modules.insert(module) } } label: { Label(module.title, systemImage: module.icon).frame(maxWidth: .infinity) }.buttonStyle(.borderedProminent).tint(modules.contains(module) ? module.color : .gray.opacity(0.22)) } }; Toggle("重要", isOn: $important).padding(13).background(.white.opacity(0.48), in: RoundedRectangle(cornerRadius: 16)); if dateStart != nil || minimumAmount != nil || maximumAmount != nil || category != nil || !tags.isEmpty { Text(filterSummary).font(.caption).foregroundStyle(.secondary) } }; searchCard("结果 \(results.count)", "list.bullet", .indigo) { VStack(spacing: 10) { ForEach(results) { record in Button { focused = nil; selectedRecord = record } label: { SearchResultRow(record: record).padding(.horizontal, 12).contentShape(Rectangle()) }.buttonStyle(.plain).background(.white.opacity(0.58), in: RoundedRectangle(cornerRadius: 18)).overlay(RoundedRectangle(cornerRadius: 18).stroke(.white.opacity(0.8))) } } } }.padding(16).background(Color.clear.contentShape(Rectangle()).onTapGesture { focused = nil }) }.scrollDismissesKeyboard(.interactively).background(LakeBackground()).navigationTitle("搜索").navigationBarTitleDisplayMode(.inline).navigationDestination(item: $selectedRecord) { DetailView(record: $0) }.onAppear { focused = nil; search() }.onDisappear { focused = nil }.onChange(of: keyword) { search() }.onChange(of: modules) { search() }.onChange(of: important) { search() }.toolbar { ToolbarItemGroup(placement: .keyboard) { Spacer(); Button("完成") { focused = nil } } } }
    private var totalMap: [String: Decimal] { QuickNoteCore.numericTotals(in: results) }
    private var totalKeys: [String] { totalMap.keys.sorted() }
    private var filterSummary: String { [dateStart == nil ? nil : "日期范围", minimumAmount.map { "金额 \(minimumInclusive ? "≥" : ">") \($0)" }, maximumAmount.map { "金额 \(maximumInclusive ? "≤" : "<") \($0)" }, currency, category, tags.isEmpty ? nil : tags.joined(separator: "、")].compactMap { $0 }.joined(separator: " · ") }
    private func search() { do { results = try model.core.search(RecordQuery(keyword: keyword, modules: modules, importantOnly: important, tags: tags, dateStart: dateStart, dateEnd: dateEnd, minimumAmount: minimumAmount, minimumInclusive: minimumInclusive, maximumAmount: maximumAmount, maximumInclusive: maximumInclusive, currency: currency, category: category)) } catch { model.error = error.localizedDescription } }
    private func searchCard<Content: View>(_ title: String, _ icon: String, _ color: Color, @ViewBuilder content: () -> Content) -> some View { VStack(alignment: .leading, spacing: 15) { HStack { Image(systemName: icon).foregroundStyle(color).frame(width: 42, height: 42).background(color.opacity(0.13), in: RoundedRectangle(cornerRadius: 13)); Text(title).font(.title2.bold()).foregroundStyle(AppTheme.primary); Spacer() }; content() }.frame(maxWidth: .infinity, alignment: .leading).padding(18).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 28)).background(color.opacity(0.035), in: RoundedRectangle(cornerRadius: 28)).overlay(RoundedRectangle(cornerRadius: 28).stroke(.white.opacity(0.95), lineWidth: 1.2)).shadow(color: color.opacity(0.15), radius: 16, y: 8) }
}

struct SearchResultRow: View { let record: Record; var body: some View { HStack(spacing: 12) { Image(systemName: record.module.icon).foregroundStyle(record.module.color).frame(width: 42, height: 42).background(record.module.color.opacity(0.12), in: RoundedRectangle(cornerRadius: 12)); VStack(alignment: .leading, spacing: 4) { Text(record.content).font(.headline).lineLimit(1); Text(record.rawInput).font(.caption).foregroundStyle(.secondary).lineLimit(1); HStack { Text(record.module.title); ForEach(record.tags.prefix(2), id: \.self) { Text($0) } }.font(.caption2).foregroundStyle(record.module.color) }; Spacer(); VStack(alignment: .trailing) { Text(record.occurredAt ?? record.createdAt, style: .date).font(.caption).foregroundStyle(.secondary); ForEach(record.amountItems.prefix(3), id: \.self) { Text("\($0.currency ?? "") \($0.value)").font(.headline).foregroundStyle(.blue) } }; Image(systemName: "chevron.right").foregroundStyle(.secondary) }.padding(.vertical, 12).frame(maxWidth: .infinity).contentShape(Rectangle()) } }

struct DetailView: View {
    @EnvironmentObject private var model: AppModel; @Environment(\.dismiss) private var dismiss; @State private var record: Record; @State private var lastParsedRaw: String
    init(record: Record) { _record = State(initialValue: record); _lastParsedRaw = State(initialValue: record.rawInput) }
    var body: some View { RecordForm(record: $record, showRawInput: true, showsDetailSummary: true, onSave: saveAndDismiss, onAutoSave: save).navigationTitle("记录详情").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItemGroup(placement: .bottomBar) { ShareLink(item: shareText) { Label("分享", systemImage: "square.and.arrow.up") }; Spacer(); ShareLink(item: shareText) { Label("导出", systemImage: "doc") }; Spacer(); Menu { Button("复制内容") { UIPasteboard.general.string = shareText } } label: { Label("更多", systemImage: "ellipsis") } } }.task(id: record.rawInput) { try? await Task.sleep(for: .milliseconds(400)); guard !Task.isCancelled, record.rawInput != lastParsedRaw else { return }; await reparseAndSave() } }
    private var shareText: String { [record.content, record.rawInput == record.content ? nil : record.rawInput].compactMap { $0 }.joined(separator: "\n\n") }
    private func save(_ value: Record) { do { try model.save(value); record = value } catch { model.error = error.localizedDescription } }
    private func saveAndDismiss(_ value: Record) { do { try model.save(value); record = value; dismiss() } catch { model.error = error.localizedDescription } }
    private func reparseAndSave() async { let raw = record.rawInput.trimmed; guard !raw.isEmpty else { return }; do { if case .create(var parsed) = try await model.parser.parse(raw) { parsed.id = record.id; parsed.ownerID = record.ownerID; parsed.createdAt = record.createdAt; parsed.important = record.important; lastParsedRaw = raw; save(parsed) } } catch { model.error = "重新解析失败，已保留当前记录。" } }
}

struct RecordForm: View {
    @EnvironmentObject private var model: AppModel; @Binding var record: Record; let showRawInput: Bool; let showsDetailSummary: Bool; let saveTitle: String; let onSave: (Record) -> Void; let onSearch: ((Record) -> Void)?; let onReparse: (() -> Void)?; let onVoice: (() -> Void)?; let onAutoSave: ((Record) -> Void)?; let isRecording: Bool; let voiceLabel: String
    @State private var tags: String; @State private var amount: String; @State private var attachmentMenu = false; @State private var photos = false; @State private var camera = false; @State private var photo: PhotosPickerItem?; @FocusState private var focused: AppFocus?
    init(record: Binding<Record>, showRawInput: Bool, showsDetailSummary: Bool = false, saveTitle: String = "保存", onSave: @escaping (Record) -> Void, onSearch: ((Record) -> Void)? = nil, onReparse: (() -> Void)? = nil, onVoice: (() -> Void)? = nil, onAutoSave: ((Record) -> Void)? = nil, isRecording: Bool = false, voiceLabel: String = "语音补充") { _record = record; self.showRawInput = showRawInput; self.showsDetailSummary = showsDetailSummary; self.saveTitle = saveTitle; self.onSave = onSave; self.onSearch = onSearch; self.onReparse = onReparse; self.onVoice = onVoice; self.onAutoSave = onAutoSave; self.isRecording = isRecording; self.voiceLabel = voiceLabel; _tags = State(initialValue: record.wrappedValue.tags.joined(separator: ", ")); _amount = State(initialValue: record.wrappedValue.amount.map(String.init(describing:)) ?? "") }
    var body: some View { ScrollView { VStack(spacing: 16) { if showsDetailSummary { detailSummary }; card { Picker("模块", selection: $record.module) { ForEach(Module.allCases) { Label($0.title, systemImage: $0.icon).tag($0) } }.pickerStyle(.segmented) }; if showRawInput { card(title: "记录原文", icon: "square.and.pencil", color: .blue, trailing: onReparse == nil ? nil : { focused = nil; onReparse?() }) { TextField("记录原文", text: $record.rawInput, axis: .vertical).focused($focused, equals: .raw).font(.body).lineLimit(3...8).submitLabel(.done).onSubmit { focused = nil; autoSave() } } }; card(title: "内容", icon: "sparkles", color: .purple) { Text(record.content).font(.body).frame(maxWidth: .infinity, alignment: .leading).textSelection(.enabled) }; HStack(alignment: .top, spacing: 12) { card(title: "标签", icon: "tag.fill", color: .purple) { TextField("逗号分隔", text: $tags).focused($focused, equals: .tags).submitLabel(.done).onSubmit { focused = nil } }.frame(maxWidth: .infinity); card(title: "重要", icon: "star.fill", color: .orange) { Toggle("", isOn: $record.important).labelsHidden() }.frame(width: 124).frame(minHeight: 128) }; moduleFields }.padding(.horizontal, 16).padding(.vertical, 18).background(Color.clear.contentShape(Rectangle()).onTapGesture { focused = nil }) }.scrollDismissesKeyboard(.interactively).background(LakeBackground()).safeAreaInset(edge: .bottom) { if let onVoice { captureBar(onVoice) } }.toolbar { ToolbarItemGroup(placement: .topBarTrailing) { if let onSearch { Button { focused = nil; if let value = prepared() { onSearch(value) } } label: { Label("搜索", systemImage: "magnifyingglass") } }; Button(saveTitle) { focused = nil; if let value = prepared() { onSave(value) } }.buttonStyle(.borderedProminent) }; ToolbarItemGroup(placement: .keyboard) { Spacer(); Button("完成") { focused = nil } } }.confirmationDialog("添加图片", isPresented: $attachmentMenu) { Button("拍照") { if UIImagePickerController.isSourceTypeAvailable(.camera) { camera = true } else { model.error = "当前设备没有可用相机。" } }; Button("从相册选择") { photos = true }; Button("取消", role: .cancel) {} }.photosPicker(isPresented: $photos, selection: $photo, matching: .images).sheet(isPresented: $camera) { CameraPicker() }.onChange(of: record.tags) { tags = $0.joined(separator: ", ") }.onChange(of: record.amount) { amount = $0.map(String.init(describing:)) ?? "" }.onChange(of: focused) { old, new in if old == .raw && new != .raw { autoSave() } }.onChange(of: record.module) { _ in autoSave() }.onChange(of: record.important) { _ in autoSave() }.onChange(of: record.reminderEnabled) { _ in autoSave() }.onChange(of: record.status) { _ in autoSave() }.onChange(of: record.occurredAt) { _ in autoSave() }.onChange(of: record.dueAt) { _ in autoSave() }.onDisappear { focused = nil } }
    private func captureBar(_ onVoice: @escaping () -> Void) -> some View { HStack(spacing: 10) { Button { focused = nil; onVoice() } label: { VStack(spacing: 3) { Image(systemName: isRecording ? "waveform" : "mic.fill").font(.title2); Text(voiceLabel).font(.caption2) }.frame(width: 72, height: 58).foregroundStyle(isRecording ? .white : .blue).background(isRecording ? .blue : .white.opacity(0.85), in: Circle()).shadow(color: .blue.opacity(0.18), radius: 9) }; HStack { TextField("继续说，补充或修改…", text: $record.rawInput).focused($focused, equals: .raw).submitLabel(.search).onSubmit { focused = nil; if let value = prepared() { onSearch?(value) } }; Button { focused = nil; if let value = prepared() { onSearch?(value) } } label: { Image(systemName: "magnifyingglass").font(.title2) } }.padding(.horizontal, 16).frame(height: 58).background(.white.opacity(0.8), in: Capsule()); Button { focused = nil; attachmentMenu = true } label: { Image(systemName: "plus").font(.title2).frame(width: 54, height: 54).background(.white.opacity(0.85), in: Circle()) } }.padding(12).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 30)).padding(.horizontal, 8) }
    private var detailSummary: some View { HStack(spacing: 16) { Image(systemName: record.module.icon).font(.system(size: 34, weight: .semibold)).foregroundStyle(record.module.color).frame(width: 72, height: 72).background(record.module.color.opacity(0.14), in: RoundedRectangle(cornerRadius: 22)); VStack(alignment: .leading, spacing: 5) { Text(record.module.title).font(.headline).foregroundStyle(record.module.color); Text(record.content).font(.title3.bold()).lineLimit(2); Text(record.occurredAt ?? record.createdAt, style: .date).font(.caption).foregroundStyle(.secondary) }; Spacer(); Image(systemName: record.important ? "star.fill" : "star").foregroundStyle(.orange) }.padding(20).frame(maxWidth: .infinity, alignment: .leading).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 30)).overlay(RoundedRectangle(cornerRadius: 30).stroke(.white.opacity(0.95))).shadow(color: record.module.color.opacity(0.16), radius: 18, y: 8) }
    @ViewBuilder private var moduleFields: some View { switch record.module { case .ledger: VStack(spacing: 12) { fieldCard("商家", "storefront.fill", .blue) { optional("商家", $record.merchant, .merchant) }; if record.amountItems.count > 1 { card(title: "金额明细", icon: "banknote.fill", color: .orange) { LazyVGrid(columns: [.init(.flexible()), .init(.flexible())], spacing: 10) { ForEach(record.amountItems, id: \.self) { item in VStack(alignment: .leading) { Text(item.currency ?? "未标币种").font(.caption).foregroundStyle(.secondary); Text(String(describing: item.value)).font(.title3.bold()) }.frame(maxWidth: .infinity, alignment: .leading).padding(12).background(.white.opacity(0.58), in: RoundedRectangle(cornerRadius: 15)) } } } } else { HStack(alignment: .top, spacing: 12) { fieldCard("金额", "banknote.fill", .orange) { TextField("金额", text: $amount).keyboardType(.decimalPad).focused($focused, equals: .amount) }; fieldCard("货币", "coloncurrencysign.circle.fill", .green) { optional("币种", $record.currency, .currency) } } }; HStack(alignment: .top, spacing: 12) { fieldCard("类别", "tag.fill", .purple) { optional("类别", $record.category, .category) }; fieldCard("支付方式", "creditcard.fill", .orange) { optional("支付方式", $record.paymentMethod, .payment) } }; HStack(alignment: .top, spacing: 12) { fieldCard("地点", "mappin.circle.fill", .mint) { optional("地点", $record.location, .location) }.frame(maxWidth: .infinity); fieldCard("日期时间", "calendar", .indigo) { date("日期时间", $record.occurredAt) }.frame(maxWidth: .infinity) } }; case .todo: VStack(spacing: 12) { card(title: "待办时间", icon: "calendar", color: .indigo) { date("日期时间", $record.dueAt) }; HStack { card(title: "提醒", icon: "bell.fill", color: .orange) { Toggle("提醒", isOn: $record.reminderEnabled) }; card(title: "状态", icon: "checkmark.circle.fill", color: .green) { Picker("状态", selection: Binding(get: { record.status ?? .pending }, set: { record.status = $0 })) { ForEach(TodoStatus.allCases, id: \.self) { Text($0.rawValue).tag($0) } } } }; card(title: "地点", icon: "mappin.circle.fill", color: .mint) { optional("地点", $record.location, .location) } }; case .memo: card(title: "提醒", icon: "bell.fill", color: .orange) { Toggle("提醒", isOn: $record.reminderEnabled) }; case .idea: EmptyView() } }
    private func card<Content: View>(title: String? = nil, icon: String? = nil, color: Color = .blue, trailing: (() -> Void)? = nil, @ViewBuilder content: () -> Content) -> some View { VStack(alignment: .leading, spacing: 13) { if let title { HStack { if let icon { Image(systemName: icon).font(.headline).foregroundStyle(color).frame(width: 40, height: 40).background(color.opacity(0.14), in: RoundedRectangle(cornerRadius: 13)) }; Text(title).font(.headline).foregroundStyle(AppTheme.primary); Spacer(); if let trailing { Button(action: trailing) { Image(systemName: "arrow.clockwise").frame(width: 34, height: 34).background(.white.opacity(0.7), in: Circle()) } } } }; content() }.frame(maxWidth: .infinity, alignment: .leading).padding(17).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 26)).background(LinearGradient(colors: [.white.opacity(0.72), color.opacity(0.055)], startPoint: .topLeading, endPoint: .bottomTrailing), in: RoundedRectangle(cornerRadius: 26)).overlay(RoundedRectangle(cornerRadius: 26).stroke(.white.opacity(0.95), lineWidth: 1.2)).shadow(color: color.opacity(0.14), radius: 14, y: 7) }
    private func fieldCard<Content: View>(_ title: String, _ icon: String, _ color: Color, @ViewBuilder content: () -> Content) -> some View { card(title: title, icon: icon, color: color) { content() }.frame(minHeight: 112, alignment: .top) }
    private func optional(_ title: String, _ value: Binding<String?>, _ field: AppFocus) -> some View { TextField(title, text: Binding(get: { value.wrappedValue ?? "" }, set: { value.wrappedValue = $0.isEmpty ? nil : $0 })).focused($focused, equals: field).submitLabel(.done).onSubmit { focused = nil } }
    private func date(_ title: String, _ value: Binding<Date?>) -> some View { VStack(alignment: .leading) { Toggle("设置", isOn: Binding(get: { value.wrappedValue != nil }, set: { value.wrappedValue = $0 ? Date() : nil })); if value.wrappedValue != nil { DatePicker(title, selection: Binding(get: { value.wrappedValue! }, set: { value.wrappedValue = $0 }), displayedComponents: [.date, .hourAndMinute]).labelsHidden() } } }
    private func autoSave() { guard onAutoSave != nil, let value = prepared() else { return }; onAutoSave?(value) }
    private func prepared() -> Record? { focused = nil; var value = record; value.tags = tags.csv; guard amount.isEmpty || Decimal(string: amount) != nil else { model.error = "金额格式无效"; return nil }; if value.module == .ledger, value.amountItems.count <= 1 { value.amount = amount.isEmpty ? nil : Decimal(string: amount); value.amountItems = value.amount.map { [AmountItem(value: $0, currency: value.currency)] } ?? [] }; record = value; return value }
}

struct RecordRow: View { let record: Record; var body: some View { VStack(alignment: .leading) { Text(record.content).lineLimit(2); Text(record.occurredAt ?? record.createdAt, style: .date).font(.caption).foregroundStyle(.secondary) } } }

struct CameraPicker: UIViewControllerRepresentable {
    @Environment(\.dismiss) private var dismiss
    func makeCoordinator() -> Coordinator { Coordinator(dismiss: dismiss) }
    func makeUIViewController(context: Context) -> UIImagePickerController { let picker = UIImagePickerController(); picker.sourceType = .camera; picker.delegate = context.coordinator; return picker }
    func updateUIViewController(_ uiViewController: UIImagePickerController, context: Context) {}
    final class Coordinator: NSObject, UIImagePickerControllerDelegate, UINavigationControllerDelegate { let dismiss: DismissAction; init(dismiss: DismissAction) { self.dismiss = dismiss }; func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any]) { dismiss() }; func imagePickerControllerDidCancel(_ picker: UIImagePickerController) { dismiss() } }
}

@MainActor final class SpeechInput: ObservableObject {
    enum Phase { case idle, listening, processing }
    @Published var transcript = ""; @Published var finishedTranscript: String?; @Published var phase: Phase = .idle; @Published var error: String?
    var isRecording: Bool { phase == .listening }; var statusText: String { phase == .listening ? "正在听…" : phase == .processing ? "正在识别…" : "语音补充" }
    let primaryLocale = Locale(identifier: "zh-CN")
    let secondaryLocale = Locale(identifier: "en-US")
    private let engine = AVAudioEngine(); private var task: SFSpeechRecognitionTask?; private var request: SFSpeechAudioBufferRecognitionRequest?; private var tapInstalled = false
    func start() { SFSpeechRecognizer.requestAuthorization { [weak self] status in Task { @MainActor in guard status == .authorized else { self?.error = "请允许语音识别权限。"; return }; AVAudioApplication.requestRecordPermission { allowed in Task { @MainActor in guard allowed else { self?.error = "请允许麦克风权限。"; return }; self?.begin() } } } } }
    private func begin() { tearDown(); transcript = ""; finishedTranscript = nil; guard let recognizer = SFSpeechRecognizer(locale: primaryLocale), recognizer.isAvailable else { error = "系统语音识别不可用。"; return }; let request = SFSpeechAudioBufferRecognitionRequest(); request.shouldReportPartialResults = true; request.contextualStrings = ["沃尔玛", "Target", "Costco", "Amazon", "Visa", "Starbucks", "iPhone"]; self.request = request; let node = engine.inputNode; node.installTap(onBus: 0, bufferSize: 1024, format: node.outputFormat(forBus: 0)) { buffer, _ in request.append(buffer) }; tapInstalled = true; task = recognizer.recognitionTask(with: request) { [weak self] result, failure in Task { @MainActor in guard let self else { return }; if let result { self.transcript = result.bestTranscription.formattedString }; if failure != nil || result?.isFinal == true { self.finish() } } }; do { try AVAudioSession.sharedInstance().setCategory(.record, mode: .measurement); try AVAudioSession.sharedInstance().setActive(true); engine.prepare(); try engine.start(); phase = .listening } catch { tearDown(); self.error = "无法启动麦克风：\(error.localizedDescription)" } }
    private func finish() { guard request != nil || task != nil else { return }; phase = .processing; let finalText = transcript; tearDown(); if !finalText.trimmed.isEmpty { finishedTranscript = finalText }; phase = .idle }
    func stop() { guard phase != .idle else { return }; finish() }
    private func tearDown() { if engine.isRunning { engine.stop() }; if tapInstalled { engine.inputNode.removeTap(onBus: 0); tapInstalled = false }; request?.endAudio(); task?.cancel(); request = nil; task = nil }
}

private extension String { var trimmed: String { trimmingCharacters(in: .whitespacesAndNewlines) }; var csv: [String] { split(separator: ",").map { String($0).trimmed }.filter { !$0.isEmpty } } }
private extension Module { var icon: String { switch self { case .ledger: "chart.bar.fill"; case .todo: "checkmark.square.fill"; case .memo: "note.text"; case .idea: "lightbulb.fill" } }; var decoration: String { switch self { case .ledger: "creditcard.fill"; case .todo: "checklist"; case .memo: "note.text"; case .idea: "sparkles" } }; var subtitle: String { switch self { case .ledger: "轻松记账，清楚每一笔"; case .todo: "记下任务，安心完成"; case .memo: "随手记录，整理生活"; case .idea: "闪现的想法，值得记录" } }; var color: Color { switch self { case .ledger: AppTheme.ledgerAccent; case .todo: AppTheme.todoAccent; case .memo: AppTheme.memoAccent; case .idea: AppTheme.ideaAccent } } }
