import SwiftUI
import Speech
import AVFoundation
import PhotosUI
import UIKit
import EventKit
import UniformTypeIdentifiers

@MainActor private enum AppTheme {
    static var background: LinearGradient { let color = SkinManager.shared.color("appBackground") ?? Color(red: 0.91, green: 0.96, blue: 1); return LinearGradient(colors: [color, .white, color.opacity(0.9)], startPoint: .topLeading, endPoint: .bottomTrailing) }
    static var surface: Color { SkinManager.shared.color("surface") ?? .white.opacity(0.78) }; static var surfaceAlt: Color { surface.opacity(0.8) }; static var primary: Color { SkinManager.shared.color("primary") ?? Color(red: 0.04, green: 0.15, blue: 0.34) }
    static var accent: Color { SkinManager.shared.color("accent") ?? .indigo }; static var textPrimary: Color { SkinManager.shared.color("textPrimary") ?? primary }; static var textSecondary: Color { SkinManager.shared.color("textSecondary") ?? .secondary }; static var border: Color { SkinManager.shared.color("border") ?? .white.opacity(0.95) }; static var navigation: Color { SkinManager.shared.color("navigation") ?? surface }; static var tabBar: Color { SkinManager.shared.color("tabBar") ?? surface }; static var buttonPrimary: Color { SkinManager.shared.color("buttonPrimary") ?? .blue }
    static var ledgerAccent: Color { SkinManager.shared.color("ledgerAccent") ?? .blue }; static var todoAccent: Color { SkinManager.shared.color("todoAccent") ?? .green }; static var memoAccent: Color { SkinManager.shared.color("memoAccent") ?? .orange }; static var ideaAccent: Color { SkinManager.shared.color("ideaAccent") ?? .purple }
    static let cornerRadius: CGFloat = 24, shadow = Color.blue.opacity(0.1), spacing: CGFloat = 14
}
private let appLanguageCode = Locale.preferredLanguages.first ?? "en"
private enum AppFocus: Hashable { case homeInput, searchInput, raw, tags, merchant, amount, currency, category, payment, location }

private struct LakeBackground: View {
    var lightweight = false
    var body: some View { ZStack { AppTheme.background; if let image = SkinManager.shared.image("pageBackgroundImage") { Image(uiImage: image).resizable().scaledToFill().ignoresSafeArea() } else { if !lightweight { Circle().fill(.cyan.opacity(0.16)).frame(width: 360).blur(radius: 75).offset(x: 170, y: -260); Circle().fill(.orange.opacity(0.1)).frame(width: 250).blur(radius: 65).offset(x: -150, y: -170) }; Image(systemName: "mountain.2.fill").resizable().scaledToFit().frame(width: 520).foregroundStyle(LinearGradient(colors: [.blue.opacity(0.13), .cyan.opacity(0.025)], startPoint: .top, endPoint: .bottom)).offset(y: -95) }; if !lightweight { Rectangle().fill(.white.opacity(0.28)).frame(height: 210).blur(radius: 24).offset(y: 90); if let header = SkinManager.shared.image("headerDecoration") { VStack { Image(uiImage: header).resizable().scaledToFit().frame(maxWidth: 500); Spacer() }.padding(.top, 80) } }; if !lightweight, SkinManager.shared.current.effects.globalEffectEnabled, SkinManager.shared.current.effects.globalEffectType == "falling", let effect = SkinManager.shared.image("globalEffectLayer") { FallingEffect(image: effect) } }.ignoresSafeArea() }
}

struct SkinDefinition: Codable, Equatable, Identifiable {
    struct Effects: Codable, Equatable { var globalEffectEnabled: Bool; var globalEffectType: String }
    var schemaVersion: Int; var id: String; var name: String; var author: String?; var colors: [String: String]; var assets: [String: String]; var effects: Effects
    static let `default` = SkinDefinition(schemaVersion: 1, id: "lake-light", name: "Default / Lake Light", author: "AIQuickNote", colors: [:], assets: [:], effects: .init(globalEffectEnabled: false, globalEffectType: "none"))
}

enum SkinError: Error { case malformedArchive, unsupportedSchema, invalidManifest, unsafePath, missingAsset, invalidImage, forbiddenContent }

@MainActor final class SkinManager: ObservableObject {
    static let shared = SkinManager()
    @Published private(set) var current: SkinDefinition = .default; @Published private(set) var installed: [SkinDefinition] = []
    private var entries: [String: Data] = [:], images: [String: UIImage] = [:]; private let defaults: UserDefaults; private let folder: URL
    init(defaults: UserDefaults = .standard, folder: URL? = nil) { self.defaults = defaults; self.folder = folder ?? FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].appendingPathComponent("Skins", isDirectory: true); reload() }
    static func validate(_ data: Data) throws -> (SkinDefinition, [String: Data]) {
        let entries: [String: Data]; do { entries = try ZipArchive.entries(in: data, requiredEntry: "skin.json") } catch { throw SkinError.malformedArchive }
        let forbidden = ["swift", "sh", "js", "dylib", "so", "framework", "app", "exe"]
        for path in entries.keys { let normalized = path.replacingOccurrences(of: "\\", with: "/"); if normalized.hasPrefix("/") || normalized.contains("../") || normalized.contains(":") { throw SkinError.unsafePath }; if forbidden.contains(URL(fileURLWithPath: normalized).pathExtension.lowercased()) { throw SkinError.forbiddenContent } }
        guard let manifest = entries["skin.json"], let skin = try? JSONDecoder().decode(SkinDefinition.self, from: manifest), !skin.id.trimmed.isEmpty, !skin.name.trimmed.isEmpty, skin.id.range(of: #"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"#, options: .regularExpression) != nil else { throw SkinError.invalidManifest }
        guard skin.schemaVersion == 1, ["none", "falling"].contains(skin.effects.globalEffectType) else { throw SkinError.unsupportedSchema }
        for path in skin.assets.values { guard path.hasPrefix("assets/"), let data = entries[path] else { throw SkinError.missingAsset }; guard UIImage(data: data) != nil else { throw SkinError.invalidImage } }
        return (skin, entries)
    }
    func importSkin(_ data: Data) throws { let (skin, _) = try Self.validate(data); try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true); try data.write(to: folder.appendingPathComponent("\(skin.id).aiqskin"), options: .atomic); reload(); try apply(skin.id) }
    func apply(_ id: String) throws { guard id != SkinDefinition.default.id else { current = .default; entries = [:]; images = [:]; defaults.set(id, forKey: "skin.current"); return }; let url = folder.appendingPathComponent("\(id).aiqskin"), result = try Self.validate(Data(contentsOf: url)); current = result.0; entries = result.1; images = [:]; defaults.set(id, forKey: "skin.current") }
    func delete(_ id: String) { guard id != SkinDefinition.default.id else { return }; try? FileManager.default.removeItem(at: folder.appendingPathComponent("\(id).aiqskin")); if current.id == id { try? apply(SkinDefinition.default.id) }; reload() }
    func color(_ key: String) -> Color? { current.colors[key].flatMap(Color.init(hex:)) }
    func image(_ key: String) -> UIImage? { guard let path = current.assets[key] else { return nil }; if let cached = images[path] { return cached }; guard let data = entries[path], let image = UIImage(data: data) else { return nil }; images[path] = image; return image }
    private func reload() { installed = ((try? FileManager.default.contentsOfDirectory(at: folder, includingPropertiesForKeys: nil)) ?? []).compactMap { url in guard let data = try? Data(contentsOf: url), let result = try? Self.validate(data) else { return nil }; return result.0 }; let saved = defaults.string(forKey: "skin.current") ?? SkinDefinition.default.id; do { try apply(saved) } catch { try? apply(SkinDefinition.default.id) } }
}

private extension Color { init?(hex: String) { var value = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#")); guard value.count == 6 || value.count == 8 else { return nil }; if value.count == 6 { value += "FF" }; guard let raw = UInt64(value, radix: 16) else { return nil }; self.init(red: Double((raw >> 24) & 255) / 255, green: Double((raw >> 16) & 255) / 255, blue: Double((raw >> 8) & 255) / 255, opacity: Double(raw & 255) / 255) } }
private struct FallingEffect: View { let image: UIImage; var body: some View { GeometryReader { proxy in ForEach(0..<12, id: \.self) { i in Image(uiImage: image).resizable().scaledToFit().frame(width: CGFloat(18 + i % 4 * 7)).opacity(0.45).position(x: proxy.size.width * CGFloat((i * 37) % 100) / 100, y: proxy.size.height * CGFloat((i * 53) % 100) / 100) } }.allowsHitTesting(false) } }

final class IdentitySession: IdentityGate, ObservableObject, @unchecked Sendable {
    @Published private(set) var currentUser: IdentityUser?
    let legacyOwnerID: String?
    var confirmedUserID: String? { currentUser?.id }
    var isAuthenticated: Bool { currentUser != nil }
    init(defaults: UserDefaults = .standard) {
        if let data = defaults.data(forKey: "identity.currentUser"), let user = try? JSONDecoder().decode(IdentityUser.self, from: data) { currentUser = user; legacyOwnerID = nil }
        else if let legacy = defaults.string(forKey: "confirmedUserID") { currentUser = IdentityUser(id: "00000000-0000-4000-8000-000000000101", provider: .apple, providerSubject: "mock-apple-user-001", displayName: "Test User 1", email: "test1@example.invalid", createdAt: Date(timeIntervalSince1970: 0)); legacyOwnerID = legacy; persist(defaults) }
        else { currentUser = nil; legacyOwnerID = nil }
    }
    func signIn(_ user: IdentityUser, defaults: UserDefaults = .standard) { currentUser = user; persist(defaults) }
    func signOut(defaults: UserDefaults = .standard) { currentUser = nil; defaults.removeObject(forKey: "identity.currentUser"); defaults.removeObject(forKey: "confirmedUserID") }
    private func persist(_ defaults: UserDefaults) { if let currentUser, let data = try? JSONEncoder().encode(currentUser) { defaults.set(data, forKey: "identity.currentUser"); defaults.set(currentUser.id, forKey: "confirmedUserID") } }
}

enum ReminderServiceError: Error { case permissionDenied }

@MainActor final class ReminderService: ObservableObject {
    @Published private(set) var status = EKEventStore.authorizationStatus(for: .reminder)
    private let store = EKEventStore()
    var statusText: String { switch status { case .fullAccess, .writeOnly: "已允许"; case .denied, .restricted: "未允许"; case .notDetermined: "未请求"; @unknown default: "未知" } }
    func create(for record: Record) async throws -> String {
        if status == .notDetermined { _ = try await store.requestFullAccessToReminders(); status = EKEventStore.authorizationStatus(for: .reminder) }
        guard status == .fullAccess || status == .writeOnly else { throw ReminderServiceError.permissionDenied }
        let reminder = EKReminder(eventStore: store); reminder.title = record.content; reminder.calendar = store.defaultCalendarForNewReminders(); if let due = record.dueAt { reminder.dueDateComponents = Calendar.current.dateComponents(in: TimeZone.current, from: due) }; reminder.notes = "来自 AI随手记"; try store.save(reminder, commit: true); return reminder.calendarItemIdentifier
    }
    func exists(_ identifier: String) -> Bool { store.calendarItem(withIdentifier: identifier) != nil }
}

@MainActor final class AppModel: ObservableObject {
    @Published var records: [Record] = []; @Published var error: String?; @Published var loginPresented = false
    let identity: IdentitySession; let core: QuickNoteCore; let parser = DeterministicDraftParser(); let reminderService = ReminderService()
    private var pendingSave: Record?; private var pendingSaveCompletion: (() -> Void)?
    init() { let folder = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0], identity = IdentitySession(), store = FileRecordStore(url: folder.appendingPathComponent("records.json")); self.identity = identity; if let old = identity.legacyOwnerID, let new = identity.confirmedUserID, var records = try? store.load(), records.contains(where: { $0.ownerID == old }) { for index in records.indices where records[index].ownerID == old { records[index].ownerID = new }; try? store.save(records) }; core = QuickNoteCore(store: store, identity: identity); reload() }
    func reload() { do { records = try core.records() } catch { self.error = error.localizedDescription } }
    func save(_ value: Record) throws { var value = value; if value.reminderEnabled, value.reminderState == .none { value.reminderState = .requested }; let saved = try core.save(value); reload(); if saved.module == .todo, saved.reminderEnabled, saved.dueAt != nil, !saved.reminderLinked { Task { await linkReminder(saved) } } }
    func saveOrRequestIdentity(_ value: Record, onSaved: @escaping () -> Void) { do { try save(value); onSaved() } catch CoreError.identityRequired { pendingSave = value; pendingSaveCompletion = onSaved; loginPresented = true } catch { self.error = error.localizedDescription } }
    func signedIn(_ user: IdentityUser) { identity.signIn(user); loginPresented = false; reload(); guard let value = pendingSave else { return }; pendingSave = nil; do { try save(value); let completion = pendingSaveCompletion; pendingSaveCompletion = nil; completion?() } catch { self.error = error.localizedDescription } }
    func signOut() { identity.signOut(); pendingSave = nil; pendingSaveCompletion = nil; reload() }
    func exportData() throws -> Data { try ExportService.makeExport(records: records, users: identity.currentUser.map { [$0] } ?? []) }
    func backupData() throws -> Data { try BackupService.makeBackup(records: records, users: identity.currentUser.map { [$0] } ?? [], settings: ["theme": "lake-light"]) }
    func restoreBackup(_ data: Data) throws { let payload = try BackupService.validateAndRead(data); try core.replaceCurrentOwnerRecords(with: payload.records); reload() }
    func reconcileReminder(_ value: Record) -> Record { guard value.reminderState == .active, let id = value.reminderExternalID, !reminderService.exists(id) else { return value }; var missing = value; missing.reminderLinked = false; missing.reminderState = .missingExternalReminder; _ = try? core.save(missing); reload(); return missing }
    private func linkReminder(_ saved: Record) async { do { var linked = saved; linked.reminderExternalID = try await reminderService.create(for: saved); linked.reminderLinked = true; linked.reminderState = .active; _ = try core.save(linked); reload() } catch { var failed = saved; failed.reminderLinked = false; failed.reminderExternalID = nil; failed.reminderState = reminderService.status == .denied || reminderService.status == .restricted ? .permissionDenied : .requested; _ = try? core.save(failed); reload(); self.error = failed.reminderState == .permissionDenied ? "提醒事项权限已关闭，请在系统设置中允许 AI随手记访问提醒事项。" : "记录已保存，但未写入系统提醒事项。" } }
}

@main struct AIQuickNoteApp: App { @StateObject private var model = AppModel(); @StateObject private var skin = SkinManager.shared; var body: some Scene { WindowGroup { RootView().environmentObject(model).environmentObject(skin).id(skin.current.id) } } }

struct RootView: View {
    @EnvironmentObject private var model: AppModel; @Environment(\.openURL) private var openURL
    var body: some View { NavigationStack { HomeView() }.tint(AppTheme.accent).sheet(isPresented: $model.loginPresented) { LoginView(onSignedIn: model.signedIn) }.alert("操作失败", isPresented: Binding(get: { model.error != nil }, set: { if !$0 { model.error = nil } })) { if model.error?.contains("权限已关闭") == true { Button("前往设置") { if let url = URL(string: UIApplication.openSettingsURLString) { openURL(url) } } }; Button("确定") {} } message: { Text(model.error ?? "未知错误") } }
}

struct LoginView: View {
    @Environment(\.dismiss) private var dismiss; @State private var selected: IdentityProvider?; let onSignedIn: (IdentityUser) -> Void
    var body: some View { NavigationStack { ZStack { LakeBackground(); ScrollView { VStack(spacing: 16) { Image(systemName: "person.crop.circle.badge.checkmark").font(.system(size: 58)).foregroundStyle(.blue); Text("登录 AI随手记").font(.largeTitle.bold()); Text("登录只用于确认本地数据归属。\n登录不会自动上传、备份或分享你的记录。").multilineTextAlignment(.center).foregroundStyle(.secondary); if let provider = selected { Text("\(provider == .x ? "X" : provider.rawValue.capitalized) 登录（开发测试）").font(.title3.bold()).padding(.top); ForEach(1...2, id: \.self) { account in Button("Test User \(account)") { signIn(provider, account) }.buttonStyle(.borderedProminent).controlSize(.large) }; Button("选择其他登录方式") { selected = nil }.buttonStyle(.borderless) } else { ForEach(IdentityProvider.allCases, id: \.self) { provider in Button { selected = provider } label: { Text("Continue with \(provider == .x ? "X" : provider.rawValue.capitalized)").frame(maxWidth: .infinity) }.buttonStyle(.borderedProminent).controlSize(.large).tint(provider == .apple ? .black : .blue) } }; Text("当前为开发测试登录，尚未连接真实第三方账号。").font(.caption).foregroundStyle(.secondary).padding(.top, 8) }.padding(24).background(.white.opacity(0.78), in: RoundedRectangle(cornerRadius: 30)).padding(20) } }.navigationTitle("身份确认").navigationBarTitleDisplayMode(.inline).toolbar { Button("取消") { dismiss() } } } }
    private func signIn(_ provider: IdentityProvider, _ account: Int) { Task { guard let user = try? await MockAuthProvider(provider).signIn(account: account) else { return }; await MainActor.run { onSignedIn(user); dismiss() } } }
}

struct AccountView: View {
    @EnvironmentObject private var model: AppModel; @Environment(\.dismiss) private var dismiss
    var body: some View { NavigationStack { ZStack { LakeBackground(); if let user = model.identity.currentUser { VStack(spacing: 14) { Image(systemName: "person.crop.circle.fill").font(.system(size: 72)).foregroundStyle(.blue); Text(user.displayName).font(.title.bold()); Text(user.provider == .x ? "X" : user.provider.rawValue.capitalized).foregroundStyle(.secondary); if let email = user.email { Text(email).foregroundStyle(.secondary) }
#if DEBUG
                    Text("ownerID …\(user.id.suffix(8))").font(.caption.monospaced()).foregroundStyle(.secondary)
#endif
                    Text("身份仅用于本地数据归属，不会自动备份、上传或分享。").multilineTextAlignment(.center).font(.footnote).foregroundStyle(.secondary).padding(); Button("退出登录", role: .destructive) { model.signOut(); dismiss() }.buttonStyle(.borderedProminent)
#if DEBUG
                    Button("切换测试用户") { model.signOut(); dismiss(); model.loginPresented = true }.buttonStyle(.bordered)
#endif
                }.padding(26).background(.white.opacity(0.78), in: RoundedRectangle(cornerRadius: 30)).padding() } }.navigationTitle("账号").navigationBarTitleDisplayMode(.inline).toolbar { Button("完成") { dismiss() } } } }
}

private let backupContentType = UTType(exportedAs: "com.example.aiquicknote.backup", conformingTo: .data)
private let skinContentType = UTType(importedAs: "com.example.aiquicknote.skin", conformingTo: .zip)

struct DataDocument: FileDocument {
    static var readableContentTypes: [UTType] { [.zip, backupContentType] }
    var data: Data
    init(_ data: Data) { self.data = data }
    init(configuration: ReadConfiguration) throws { guard let data = configuration.file.regularFileContents else { throw CocoaError(.fileReadCorruptFile) }; self.data = data }
    func fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper { FileWrapper(regularFileWithContents: data) }
}

struct DataBackupView: View {
    @EnvironmentObject private var model: AppModel; @State private var document: DataDocument?; @State private var exporting = false; @State private var importing = false; @State private var restoreConfirmation = false; @State private var pendingRestore: Data?; @State private var filename = ""; @State private var contentType = UTType.zip
    var body: some View { Form { Section("Data") { Button("Export Data") { prepareExport() }; Button("Backup Now") { prepareBackup() }; Button("Restore Backup") { importing = true } }; Section("System Integration") { LabeledContent("Reminders Permission / Status", value: model.reminderService.statusText) }; Section { Text("导出与备份只包含当前登录用户的本地记录和身份元数据，不包含密码、token 或 Keychain secrets。").font(.footnote).foregroundStyle(.secondary) } }.navigationTitle("设置").fileExporter(isPresented: $exporting, document: document, contentType: contentType, defaultFilename: filename) { if case .failure(let error) = $0 { model.error = error.localizedDescription } }.fileImporter(isPresented: $importing, allowedContentTypes: [backupContentType, .data]) { result in do { let url = try result.get(), scoped = url.startAccessingSecurityScopedResource(); defer { if scoped { url.stopAccessingSecurityScopedResource() } }; pendingRestore = try Data(contentsOf: url); _ = try BackupService.validateAndRead(pendingRestore!); restoreConfirmation = true } catch { model.error = "备份文件无效，现有数据未更改。" } }.confirmationDialog("恢复备份会覆盖当前登录用户的本地记录", isPresented: $restoreConfirmation, titleVisibility: .visible) { Button("覆盖并恢复", role: .destructive) { guard let pendingRestore else { return }; do { try model.restoreBackup(pendingRestore) } catch { model.error = "恢复失败，现有数据未更改。" } }; Button("取消", role: .cancel) {} } }
    private var dateStamp: String { let formatter = DateFormatter(); formatter.dateFormat = "yyyy-MM-dd"; return formatter.string(from: Date()) }
    private func prepareExport() { do { document = DataDocument(try model.exportData()); filename = "AIQuickNote-Export-\(dateStamp).zip"; contentType = .zip; exporting = true } catch { model.error = error.localizedDescription } }
    private func prepareBackup() { do { document = DataDocument(try model.backupData()); filename = "AIQuickNote-Backup-\(dateStamp).aiqnbackup"; contentType = backupContentType; exporting = true } catch { model.error = error.localizedDescription } }
}

enum DisplayLanguage: String, CaseIterable { case system, english, simplifiedChinese; var title: String { switch self { case .system: "Follow System"; case .english: "English"; case .simplifiedChinese: "简体中文" } } }
enum SpeechInputLanguage: String, CaseIterable { case simplifiedChinese; var title: String { "简体中文" } }

struct SettingsView: View {
    @EnvironmentObject private var model: AppModel; @Environment(\.dismiss) private var dismiss; @Environment(\.openURL) private var openURL
    @AppStorage("language.display") private var displayLanguage = DisplayLanguage.system.rawValue; @AppStorage("language.speech") private var speechLanguage = SpeechInputLanguage.simplifiedChinese.rawValue
    var body: some View { NavigationStack { Form {
        Section("Account") { if let user = model.identity.currentUser { LabeledContent("用户名", value: user.displayName); LabeledContent("身份", value: user.provider == .x ? "X" : user.provider.rawValue.capitalized); Button("退出登录", role: .destructive) { model.signOut(); dismiss() } } else { Text("未登录"); Button("登录") { dismiss(); model.loginPresented = true } } }
        Section("Language") { Picker("Display Language", selection: $displayLanguage) { ForEach(DisplayLanguage.allCases, id: \.rawValue) { Text($0.title).tag($0.rawValue) } }; Picker("Speech Input Language", selection: $speechLanguage) { ForEach(SpeechInputLanguage.allCases, id: \.rawValue) { Text($0.title).tag($0.rawValue) } }; LabeledContent("English mixed-language recognition", value: "Developing") }
        Section("Appearance & Skins") { NavigationLink("外观与皮肤") { SkinSettingsView() } }
        Section("Data & Backup") { NavigationLink("导出、备份与恢复") { DataBackupView() } }
        Section("Reminders & Notifications") { LabeledContent("Apple Reminders Permission", value: model.reminderService.statusText); if model.reminderService.status == .denied || model.reminderService.status == .restricted { Button("Open System Settings") { if let url = URL(string: UIApplication.openSettingsURLString) { openURL(url) } } } }
        Section("About") { LabeledContent("AI随手记", value: "V1-alpha"); LabeledContent("App Version", value: Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "—"); LabeledContent("Build Number", value: Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "—"); LabeledContent("Skin Schema Version", value: "1") }
    }.navigationTitle("Settings").toolbar { Button("完成") { dismiss() } } } }
}

struct SkinSettingsView: View {
    @EnvironmentObject private var skin: SkinManager; @EnvironmentObject private var model: AppModel; @State private var importing = false; @State private var pending: Data?; @State private var pendingName = ""; @State private var confirming = false
    var body: some View { List { Section("Current Skin") { Text(skin.current.name) }; Section("Built-in") { Button("Default / Lake Light") { try? skin.apply(SkinDefinition.default.id) } }; Section("Installed Skins") { ForEach(skin.installed) { item in HStack { Text(item.name); Spacer(); if item.id == skin.current.id { Image(systemName: "checkmark") } }.contentShape(Rectangle()).onTapGesture { try? skin.apply(item.id) } }.onDelete { offsets in offsets.map { skin.installed[$0].id }.forEach(skin.delete) }; Button("Import Skin File") { importing = true } } }.navigationTitle("外观与皮肤").fileImporter(isPresented: $importing, allowedContentTypes: [skinContentType, .zip]) { result in do { let url = try result.get(), scoped = url.startAccessingSecurityScopedResource(); defer { if scoped { url.stopAccessingSecurityScopedResource() } }; let data = try Data(contentsOf: url), validated = try SkinManager.validate(data); pending = data; pendingName = validated.0.name; confirming = true } catch { model.error = "皮肤包无效，当前皮肤未更改。" } }.confirmationDialog("预览：\(pendingName)", isPresented: $confirming, titleVisibility: .visible) { Button("Apply") { guard let pending else { return }; do { try skin.importSkin(pending) } catch { model.error = "皮肤安装失败，已回退默认皮肤。" } }; Button("取消", role: .cancel) {} } }
}

struct SharePrivacyOptions: Equatable { var showAmount = true; var showDateTime = true; var showTags = true; var showMerchantOrLocation = true }

enum SharePresentation {
    static func text(for record: Record, showAmount: Bool) -> String { guard !showAmount else { return record.content }; var text = record.content; for item in record.amountItems { let value = NSRegularExpression.escapedPattern(for: String(describing: item.value)), aliases: String; switch CurrencyCanonicalizer.canonical(item.currency) { case "USD": aliases = #"(?:USD|美元|美金|dollars?|\$)"#; case "JPY": aliases = #"(?:JPY|日元|yen|¥|￥)"#; case "EUR": aliases = #"(?:EUR|欧元|欧|euros?|€)"#; case "CNY": aliases = #"(?:CNY|RMB|人民币|元|块|¥|￥)"#; default: continue }; text = text.replacingOccurrences(of: #"(?:\#(aliases)\s*\#(value)|\#(value)\s*\#(aliases))"#, with: "•••", options: [.regularExpression, .caseInsensitive]) }; return text }
}

@MainActor enum ShareCardRenderer {
    static func png(records: [Record], options: SharePrivacyOptions, pageLabel: String? = nil) -> Data? { guard !records.isEmpty else { return nil }; let renderer = ImageRenderer(content: ShareCardView(records: records, options: options, pageLabel: pageLabel)); renderer.scale = 2; renderer.proposedSize = ProposedViewSize(width: 540, height: nil); return renderer.uiImage?.pngData() }
}

private struct ShareCardView: View {
    let records: [Record]; let options: SharePrivacyOptions; let pageLabel: String?
    var body: some View { VStack(alignment: .leading, spacing: 18) { HStack { Image(systemName: records.count == 1 ? (records.first?.module.icon ?? "note.text") : "sparkles").font(.title); Text(records.count == 1 ? (records.first?.module.title ?? "记录") : "搜索结果摘要").font(.title.bold()); Spacer(); if let pageLabel { Text(pageLabel).font(.caption).foregroundStyle(.secondary) }; if records.first?.important == true { Image(systemName: "star.fill").foregroundStyle(.orange) } }; ForEach(records.prefix(10)) { record in VStack(alignment: .leading, spacing: 8) { Text(SharePresentation.text(for: record, showAmount: options.showAmount)).font(.title3.bold()).fixedSize(horizontal: false, vertical: true); if record.module == .ledger, options.showAmount { ForEach(record.amountItems, id: \.self) { Text("\(CurrencyCanonicalizer.displayName($0.currency, languageCode: appLanguageCode) ?? "") \($0.value)").font(.headline).foregroundStyle(.blue) } }; if record.module == .todo, let status = record.status { Text(status.rawValue).foregroundStyle(.green) }; if options.showMerchantOrLocation { Text([record.merchant, record.location, record.paymentMethod].compactMap { $0 }.joined(separator: " · ")).font(.subheadline).foregroundStyle(.secondary) }; if options.showDateTime { Text(record.dueAt ?? record.occurredAt ?? record.createdAt, style: .date).font(.subheadline).foregroundStyle(.secondary) }; if options.showTags, !record.tags.isEmpty { Text(record.tags.map { "#\($0)" }.joined(separator: "  ")).font(.caption).foregroundStyle(.indigo) } }.padding(16).frame(maxWidth: .infinity, alignment: .leading).background(.white.opacity(0.82), in: RoundedRectangle(cornerRadius: 20)) }; Divider(); HStack { Spacer(); Image(systemName: "sparkles"); Text("AI随手记").font(.footnote.bold()) }.foregroundStyle(.secondary) }.padding(28).frame(width: 540).background(AppTheme.background) }
}

private struct ShareFile: Identifiable { let id = UUID(); let url: URL }
struct ShareOptionsView: View {
    @Environment(\.dismiss) private var dismiss; @State private var options = SharePrivacyOptions(); @State private var file: ShareFile?; let records: [Record]; var pageLabel: String? = nil
    var body: some View { NavigationStack { Form { Toggle("显示金额", isOn: $options.showAmount); Toggle("显示日期时间", isOn: $options.showDateTime); Toggle("显示标签", isOn: $options.showTags); Toggle("显示商家或地点", isOn: $options.showMerchantOrLocation); Button("生成 PNG 并分享") { share() }.buttonStyle(.borderedProminent).disabled(records.isEmpty) }.navigationTitle(records.count == 1 ? "分享记录" : "分享搜索摘要").toolbar { Button("取消") { dismiss() } }.sheet(item: $file) { ShareSheet(items: [$0.url]) } } }
    private func share() { guard let png = ShareCardRenderer.png(records: records, options: options, pageLabel: pageLabel) else { return }; let url = FileManager.default.temporaryDirectory.appendingPathComponent("AIQuickNote-Share-\(UUID().uuidString).png"); do { try png.write(to: url, options: .atomic); file = ShareFile(url: url) } catch {} }
}

struct ShareSheet: UIViewControllerRepresentable { let items: [Any]; func makeUIViewController(context: Context) -> UIActivityViewController { UIActivityViewController(activityItems: items, applicationActivities: nil) }; func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {} }

struct HomeView: View {
    @EnvironmentObject private var model: AppModel; @StateObject private var speech = SpeechInput()
    @State private var text = ""; @State private var draft: Record?; @State private var query: RecordQuery?; @State private var attachmentMenu = false; @State private var photos = false; @State private var camera = false; @State private var accountPresented = false; @State private var photo: PhotosPickerItem?; @FocusState private var focused: AppFocus?
    var body: some View {
        ScrollView { VStack(alignment: .leading, spacing: 12) { ZStack(alignment: .topTrailing) { VStack(alignment: .leading, spacing: 6) { Text("AI 随手记").font(.system(size: 38, weight: .bold)).foregroundStyle(AppTheme.primary); Text("记录生活，交给 AI 处理 ✨").font(.title3).foregroundStyle(.blue.opacity(0.68)); Spacer().frame(height: 12); Text(Date.now.formatted(.dateTime.month().day().weekday(.wide))).font(.headline).foregroundStyle(AppTheme.primary); Text("今天也值得被好好记录 ☀️").foregroundStyle(.blue.opacity(0.62)) }.frame(maxWidth: .infinity, alignment: .leading); VStack(alignment: .trailing, spacing: 12) { Button { if model.identity.isAuthenticated { accountPresented = true } else { model.loginPresented = true } } label: { VStack(spacing: 2) { Image(systemName: model.identity.isAuthenticated ? "person.fill.checkmark" : "person.fill").font(.title2); if !model.identity.isAuthenticated { Text("登录").font(.caption2) } }.foregroundStyle(.blue.opacity(0.7)).frame(width: 58, height: 58).background(.white.opacity(0.76), in: Circle()).overlay(Circle().stroke(.white.opacity(0.9))) }; Text("让每一个\n平凡的瞬间\n都有意义。").font(.callout.italic()).multilineTextAlignment(.trailing).foregroundStyle(.indigo.opacity(0.72)).rotationEffect(.degrees(-5)) } }.padding(.horizontal, 4); LazyVGrid(columns: [.init(.flexible()), .init(.flexible())], spacing: 14) { ForEach(Module.allCases) { module in NavigationLink(value: module) { ModuleCard(module: module, records: model.records.filter { $0.module == module }) }.simultaneousGesture(TapGesture().onEnded { focused = nil }) } } }.padding(.horizontal, 16).padding(.top, 8).padding(.bottom, 10).background(Color.clear.contentShape(Rectangle()).onTapGesture { focused = nil }) }.scrollDismissesKeyboard(.interactively)
            .background(LakeBackground()).safeAreaInset(edge: .bottom) { captureBar }.toolbar(.hidden, for: .navigationBar)
            .navigationDestination(for: Module.self) { ModuleListView(module: $0) }.navigationDestination(item: $draft) { ReviewView(draft: $0) { text = "" } }
            .navigationDestination(isPresented: Binding(get: { query != nil }, set: { if !$0 { query = nil } })) { SearchView(initialQuery: query ?? RecordQuery()) }
            .confirmationDialog("添加图片", isPresented: $attachmentMenu) { Button("拍照") { if UIImagePickerController.isSourceTypeAvailable(.camera) { camera = true } else { model.error = "当前设备没有可用相机。" } }; Button("从相册选择") { photos = true }; Button("取消", role: .cancel) {} }
            .photosPicker(isPresented: $photos, selection: $photo, matching: .images).sheet(isPresented: $camera) { CameraPicker() }
            .sheet(isPresented: $accountPresented) { SettingsView() }
            .onAppear { model.reload(); focused = nil }.onDisappear { focused = nil; speech.stop() }
            .onChange(of: speech.transcript) { text = $0 }.onChange(of: speech.finishedTranscript) { if $0 != nil { submit() } }.onChange(of: speech.error) { if let value = $0 { model.error = value } }
    }
    private var captureBar: some View { HStack(spacing: 12) {
        Button { focused = nil; speech.isRecording ? speech.stop() : speech.start() } label: { Image(systemName: speech.isRecording ? "stop.fill" : "mic.fill").font(.system(size: 34, weight: .semibold)).frame(width: 84, height: 84).background(speech.isRecording ? AnyShapeStyle(.red) : AnyShapeStyle(LinearGradient(colors: [.blue.opacity(0.65), .cyan.opacity(0.45)], startPoint: .topLeading, endPoint: .bottomTrailing))).foregroundStyle(.white).clipShape(Circle()).overlay(Circle().stroke(.white.opacity(0.9), lineWidth: 1)).shadow(color: .blue.opacity(0.3), radius: 16, y: 7) }.accessibilityLabel("语音输入")
        HStack(spacing: 8) { TextField("说一句，或输入搜索", text: $text, axis: .vertical).focused($focused, equals: .homeInput).lineLimit(1...3).submitLabel(.search).onSubmit { openSearch() }; if !text.isEmpty { Button { text = "" } label: { Image(systemName: "xmark.circle.fill").foregroundStyle(.secondary) }.accessibilityLabel("清空输入") }; Button { openSearch() } label: { Image(systemName: "magnifyingglass").font(.title2).foregroundStyle(.blue.opacity(0.8)) }.accessibilityLabel("搜索") }.padding(.horizontal, 18).frame(minHeight: 70).background(.white.opacity(0.72), in: Capsule()).overlay(Capsule().stroke(.white.opacity(0.9), lineWidth: 1)).shadow(color: .blue.opacity(0.12), radius: 12, y: 5)
        Button { focused = nil; if text.trimmed.isEmpty { attachmentMenu = true } else { submit() } } label: { Image(systemName: text.trimmed.isEmpty ? "plus" : "arrow.up").font(.system(size: 27, weight: .semibold)).frame(width: 64, height: 64).background(.white.opacity(0.8), in: Circle()).overlay(Circle().stroke(.white.opacity(0.9), lineWidth: 1)).shadow(color: .blue.opacity(0.15), radius: 10, y: 4) }.accessibilityLabel(text.trimmed.isEmpty ? "添加图片" : "提交")
    }.padding(.horizontal, 14).padding(.vertical, 12).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 36)).padding(.horizontal, 8).shadow(color: .black.opacity(0.08), radius: 16, y: -3) }
    private func submit() { let input = text.trimmed; guard !input.isEmpty else { return }; focused = nil; speech.stop(); Task { do { switch try await model.parser.parse(input) { case .create(let value): draft = value; case .search(let value): query = value } } catch { draft = Record(module: .memo, rawInput: input); model.error = "解析不可用，已保留原文供手工填写。" } } }
    private func openSearch() { focused = nil; speech.stop(); query = RecordQuery(keyword: text.trimmed) }
}

struct ModuleCard: View { let module: Module; let records: [Record]; var body: some View { ZStack(alignment: .bottomTrailing) { VStack(spacing: 5) { Image(systemName: module.decoration).font(.system(size: 48, weight: .light)); Image(systemName: "leaf.fill").font(.title) }.foregroundStyle(module.color.opacity(0.15)).padding(10); VStack(alignment: .leading, spacing: 7) { HStack { Image(systemName: module.icon).font(.title2).foregroundStyle(module.color).frame(width: 44, height: 44).background(module.color.opacity(0.13), in: RoundedRectangle(cornerRadius: 15)); Spacer(); Image(systemName: "chevron.right").foregroundStyle(AppTheme.primary.opacity(0.55)).frame(width: 32, height: 32).background(.white.opacity(0.66), in: Circle()) }; Text(module.title).font(.title2.bold()).foregroundStyle(AppTheme.primary); Text(module.subtitle).font(.caption).foregroundStyle(.secondary).lineLimit(1); VStack(alignment: .leading, spacing: 3) { ForEach(records.prefix(2)) { Text($0.content).font(.caption).lineLimit(1) }; if records.isEmpty { Text("从一句话开始记录…").font(.caption) } }.foregroundStyle(.blue.opacity(0.62)).padding(8).frame(maxWidth: .infinity, alignment: .leading).background(.white.opacity(0.42), in: RoundedRectangle(cornerRadius: 14)); Spacer(minLength: 0); Text("\(records.count) 条记录").font(.headline).foregroundStyle(module.color) }.frame(maxWidth: .infinity, minHeight: 204, alignment: .leading).padding(14) }.background(LinearGradient(colors: [.white.opacity(0.88), module.color.opacity(0.09)], startPoint: .topLeading, endPoint: .bottomTrailing), in: RoundedRectangle(cornerRadius: 30)).overlay(RoundedRectangle(cornerRadius: 30).stroke(.white.opacity(0.95), lineWidth: 1.2)).shadow(color: module.color.opacity(0.17), radius: 18, y: 9) } }

struct ReviewView: View {
    @EnvironmentObject private var model: AppModel; @Environment(\.dismiss) private var dismiss; @StateObject private var speech = SpeechInput(); @State var draft: Record; @State private var searchQuery: RecordQuery?; @State private var voicePrefix = ""; let onSaved: () -> Void
    var body: some View { RecordForm(record: $draft, showRawInput: true, saveTitle: "确认保存", onSave: save, onSearch: search, onReparse: { reparse() }, onVoice: toggleVoice, isRecording: speech.isRecording, voiceLabel: speech.statusText).navigationTitle("确认记录").navigationBarTitleDisplayMode(.inline).navigationDestination(isPresented: Binding(get: { searchQuery != nil }, set: { if !$0 { searchQuery = nil } })) { SearchView(initialQuery: searchQuery ?? RecordQuery()) }.task(id: draft.rawInput) { try? await Task.sleep(for: .milliseconds(400)); guard !Task.isCancelled else { return }; await parseCurrentInput() }.onChange(of: speech.transcript) { let value = $0.trimmed; guard !value.isEmpty else { return }; draft.rawInput = [voicePrefix, value].filter { !$0.isEmpty }.joined(separator: "，") }.onChange(of: speech.error) { if let value = $0 { model.error = value } }.onDisappear { speech.stop() } }
    private func save(_ value: Record) { model.saveOrRequestIdentity(value) { onSaved(); dismiss() } }
    private func search(_ value: Record) { draft = value; searchQuery = RecordQuery(keyword: value.merchant ?? value.paymentMethod ?? value.content, modules: [value.module], importantOnly: value.important, tags: value.tags) }
    private func reparse() { Task { await parseCurrentInput() } }
    private func toggleVoice() { if speech.isRecording { speech.stop() } else { voicePrefix = draft.rawInput.trimmed; speech.start() } }
    private func parseCurrentInput() async { let input = draft.rawInput.trimmed; guard !input.isEmpty else { return }; do { if case .create(var value) = try await model.parser.parse(input) { value.id = draft.id; value.ownerID = draft.ownerID; value.createdAt = draft.createdAt; draft = value } } catch { model.error = "重新解析失败，已保留当前内容。" } }
}

struct ModuleListView: View {
    @EnvironmentObject private var model: AppModel; @State private var adding = false; let module: Module
    var body: some View { List(model.records.filter { $0.module == module }) { record in NavigationLink(value: record) { RecordRow(record: record) }.listRowBackground(Color.white.opacity(0.78)) }.listStyle(.insetGrouped).scrollContentBackground(.hidden).scrollDismissesKeyboard(.interactively).background(LakeBackground()).navigationTitle(module.title).toolbar { Button { adding = true } label: { Image(systemName: "plus") } }.sheet(isPresented: $adding) { NavigationStack { ModuleComposerView(module: module) } }.navigationDestination(for: Record.self) { DetailView(record: $0) }.overlay { if model.records.allSatisfy({ $0.module != module }) { if let image = SkinManager.shared.image("emptyStateDecoration") { ContentUnavailableView { Label("暂无记录", systemImage: module.icon) } description: { Image(uiImage: image).resizable().scaledToFit().frame(width: 150, height: 150) } } else { ContentUnavailableView("暂无记录", systemImage: module.icon) } } }.onAppear { model.reload() } }
}

struct ModuleComposerView: View {
    @Environment(\.dismiss) private var dismiss; @State private var text = ""; @State private var draft: Record?; @FocusState private var focused: Bool; let module: Module
    var body: some View { VStack { TextField("输入一条\(module.title)记录", text: $text, axis: .vertical).focused($focused).submitLabel(.done).onSubmit { focused = false }.textFieldStyle(.roundedBorder).padding(); Button("继续") { focused = false; draft = Record(module: module, rawInput: text) }.buttonStyle(.borderedProminent).disabled(text.trimmed.isEmpty); Spacer() }.background(LakeBackground().onTapGesture { focused = false }).navigationTitle("新建\(module.title)").toolbar { Button("取消") { focused = false; dismiss() } }.navigationDestination(item: $draft) { ReviewView(draft: $0) { dismiss() } } }
}

struct SearchView: View {
    @EnvironmentObject private var model: AppModel; @State private var keyword: String; @State private var modules: Set<Module>; @State private var important: Bool; @State private var results: [Record] = []; @State private var totals: [String: Decimal] = [:]; @State private var selectedRecord: Record?; @State private var sharePresented = false; @State private var currentPage = 0; @FocusState private var focused: AppFocus?
    private let tags: [String]; private let dateStart: Date?; private let dateEnd: Date?; private let minimumAmount: Decimal?; private let minimumInclusive: Bool; private let maximumAmount: Decimal?; private let maximumInclusive: Bool; private let currency: String?; private let category: String?
    init(initialQuery: RecordQuery) { _keyword = State(initialValue: initialQuery.keyword); _modules = State(initialValue: initialQuery.modules); _important = State(initialValue: initialQuery.importantOnly); tags = initialQuery.tags; dateStart = initialQuery.dateStart; dateEnd = initialQuery.dateEnd; minimumAmount = initialQuery.minimumAmount; minimumInclusive = initialQuery.minimumInclusive; maximumAmount = initialQuery.maximumAmount; maximumInclusive = initialQuery.maximumInclusive; currency = initialQuery.currency; category = initialQuery.category }
    var body: some View { ScrollView { LazyVStack(spacing: 18) {
        searchCard("自动总额", "sum", .blue) { if totalKeys.isEmpty { Text("—").font(.title.bold()).foregroundStyle(.secondary) } else { LazyVGrid(columns: [.init(.flexible()), .init(.flexible())], spacing: 10) { ForEach(totalKeys, id: \.self) { key in HStack { VStack(alignment: .leading, spacing: 5) { Text(CurrencyCanonicalizer.displayName(key, languageCode: appLanguageCode) ?? key).font(.caption).foregroundStyle(.secondary); Text(String(describing: totals[key] ?? 0)).font(.title2.bold()).foregroundStyle(.blue) }; Spacer(); Image(systemName: "banknote.fill").foregroundStyle(Color.blue.opacity(0.35)) }.padding(14).background(Color.blue.opacity(0.09), in: RoundedRectangle(cornerRadius: 18)) } } } }
        searchCard("查询条件", "slider.horizontal.3", .purple) { HStack { Image(systemName: "magnifyingglass").foregroundStyle(.secondary); TextField("关键词", text: $keyword).focused($focused, equals: .searchInput).submitLabel(.search).onSubmit { focused = nil; currentPage = 0; search() }; if !keyword.isEmpty { Button { keyword = "" } label: { Image(systemName: "xmark.circle.fill").foregroundStyle(.secondary) } } }.padding(15).background(.white.opacity(0.68), in: RoundedRectangle(cornerRadius: 20)); LazyVGrid(columns: [.init(.flexible()), .init(.flexible())], spacing: 9) { ForEach(Module.allCases) { module in Button { if modules.contains(module) { modules.remove(module) } else { modules.insert(module) } } label: { Label(module.title, systemImage: module.icon).frame(maxWidth: .infinity) }.buttonStyle(.borderedProminent).tint(modules.contains(module) ? module.color : .gray.opacity(0.22)) } }; Toggle("重要", isOn: $important).padding(13).background(.white.opacity(0.48), in: RoundedRectangle(cornerRadius: 16)); if dateStart != nil || minimumAmount != nil || maximumAmount != nil || category != nil || !tags.isEmpty { Text(filterSummary).font(.caption).foregroundStyle(.secondary) } }
        searchCard("结果 \(results.count)", "list.bullet", .indigo) { LazyVStack(spacing: 10) { pageControls; ForEach(currentPageResults) { record in Button { focused = nil; selectedRecord = record } label: { SearchResultRow(record: record).padding(.horizontal, 12).contentShape(Rectangle()) }.buttonStyle(.plain).background(.white.opacity(0.58), in: RoundedRectangle(cornerRadius: 18)).overlay(RoundedRectangle(cornerRadius: 18).stroke(.white.opacity(0.8))) }; pageControls } }
    }.padding(16).background(Color.clear.contentShape(Rectangle()).onTapGesture { focused = nil }) }.scrollDismissesKeyboard(.interactively).background(LakeBackground(lightweight: true)).navigationTitle("搜索").navigationBarTitleDisplayMode(.inline).navigationDestination(item: $selectedRecord) { DetailView(record: $0) }.onAppear { focused = nil; search() }.onDisappear { focused = nil }.task(id: keyword) { try? await Task.sleep(for: .milliseconds(250)); guard !Task.isCancelled else { return }; currentPage = 0; search() }.onChange(of: modules) { currentPage = 0; search() }.onChange(of: important) { currentPage = 0; search() }.toolbar { ToolbarItem(placement: .topBarTrailing) { Button { focused = nil; sharePresented = true } label: { Label("分享摘要", systemImage: "square.and.arrow.up") }.disabled(results.isEmpty) }; ToolbarItemGroup(placement: .keyboard) { Spacer(); Button("完成") { focused = nil } } }.sheet(isPresented: $sharePresented) { ShareOptionsView(records: currentPageResults, pageLabel: pageLabel) } }
    private var totalKeys: [String] { totals.keys.sorted() }
    private var pageCount: Int { Pagination.pageCount(itemCount: results.count) }; private var currentPageResults: [Record] { Pagination.page(results, index: currentPage) }; private var pageLabel: String { "Page \(currentPage + 1) / \(pageCount)" }
    private var pageControls: some View { HStack { Button { currentPage -= 1 } label: { Image(systemName: "chevron.left") }.disabled(currentPage == 0); Spacer(); Text("\(currentPage + 1) / \(pageCount)").font(.subheadline.monospacedDigit()); Spacer(); Button { currentPage += 1 } label: { Image(systemName: "chevron.right") }.disabled(currentPage + 1 >= pageCount) }.padding(.vertical, 4) }
    private var filterSummary: String { [dateStart == nil ? nil : "日期范围", minimumAmount.map { "金额 \(minimumInclusive ? "≥" : ">") \($0)" }, maximumAmount.map { "金额 \(maximumInclusive ? "≤" : "<") \($0)" }, currency, category, tags.isEmpty ? nil : tags.joined(separator: "、")].compactMap { $0 }.joined(separator: " · ") }
    private func search() { let query = RecordQuery(keyword: keyword, modules: modules, importantOnly: important, tags: tags, dateStart: dateStart, dateEnd: dateEnd, minimumAmount: minimumAmount, minimumInclusive: minimumInclusive, maximumAmount: maximumAmount, maximumInclusive: maximumInclusive, currency: currency, category: category); results = QuickNoteCore.search(query, in: model.records); totals = QuickNoteCore.numericTotals(in: results) }
    private func searchCard<Content: View>(_ title: String, _ icon: String, _ color: Color, @ViewBuilder content: () -> Content) -> some View { VStack(alignment: .leading, spacing: 15) { HStack { Image(systemName: icon).foregroundStyle(color).frame(width: 42, height: 42).background(color.opacity(0.13), in: RoundedRectangle(cornerRadius: 13)); Text(title).font(.title2.bold()).foregroundStyle(AppTheme.primary); Spacer() }; content() }.frame(maxWidth: .infinity, alignment: .leading).padding(18).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 28)).background(color.opacity(0.035), in: RoundedRectangle(cornerRadius: 28)).overlay(RoundedRectangle(cornerRadius: 28).stroke(.white.opacity(0.95), lineWidth: 1.2)).shadow(color: color.opacity(0.15), radius: 16, y: 8) }
}

struct SearchResultRow: View { let record: Record; var body: some View { HStack(spacing: 12) { Image(systemName: record.module.icon).foregroundStyle(record.module.color).frame(width: 42, height: 42).background(record.module.color.opacity(0.12), in: RoundedRectangle(cornerRadius: 12)); VStack(alignment: .leading, spacing: 4) { Text(record.content).font(.headline).lineLimit(1); Text(record.rawInput).font(.caption).foregroundStyle(.secondary).lineLimit(1); HStack { Text(record.module.title); ForEach(record.tags.prefix(2), id: \.self) { Text($0) } }.font(.caption2).foregroundStyle(record.module.color) }; Spacer(); VStack(alignment: .trailing) { Text(record.occurredAt ?? record.createdAt, style: .date).font(.caption).foregroundStyle(.secondary); ForEach(record.amountItems.prefix(3), id: \.self) { Text("\(CurrencyCanonicalizer.displayName($0.currency, languageCode: appLanguageCode) ?? "") \($0.value)").font(.headline).foregroundStyle(.blue) } }; Image(systemName: "chevron.right").foregroundStyle(.secondary) }.padding(.vertical, 12).frame(maxWidth: .infinity).contentShape(Rectangle()) } }

struct DetailView: View {
    @EnvironmentObject private var model: AppModel; @Environment(\.dismiss) private var dismiss; @State private var record: Record; @State private var lastParsedRaw: String; @State private var sharePresented = false; @State private var exportDocument: DataDocument?; @State private var exporting = false
    init(record: Record) { _record = State(initialValue: record); _lastParsedRaw = State(initialValue: record.rawInput) }
    var body: some View { RecordForm(record: $record, showRawInput: true, showsDetailSummary: true, onSave: saveAndDismiss, onAutoSave: save).navigationTitle("记录详情").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItemGroup(placement: .bottomBar) { Button { sharePresented = true } label: { Label("分享", systemImage: "square.and.arrow.up") }; Spacer(); Button { export() } label: { Label("导出", systemImage: "doc") }; Spacer(); Menu { Button("复制内容") { UIPasteboard.general.string = shareText } } label: { Label("更多", systemImage: "ellipsis") } } }.task { record = model.reconcileReminder(record) }.task(id: record.rawInput) { try? await Task.sleep(for: .milliseconds(400)); guard !Task.isCancelled, record.rawInput != lastParsedRaw else { return }; await reparseAndSave() }.sheet(isPresented: $sharePresented) { ShareOptionsView(records: [record]) }.fileExporter(isPresented: $exporting, document: exportDocument, contentType: .zip, defaultFilename: "AIQuickNote-Record-\(record.id.uuidString).zip") { if case .failure(let error) = $0 { model.error = error.localizedDescription } } }
    private var shareText: String { [record.content, record.rawInput == record.content ? nil : record.rawInput].compactMap { $0 }.joined(separator: "\n\n") }
    private func save(_ value: Record) { do { try model.save(value); record = value } catch { model.error = error.localizedDescription } }
    private func saveAndDismiss(_ value: Record) { do { try model.save(value); record = value; dismiss() } catch { model.error = error.localizedDescription } }
    private func export() { do { exportDocument = DataDocument(try ExportService.makeExport(records: [record], users: model.identity.currentUser.map { [$0] } ?? [])); exporting = true } catch { model.error = error.localizedDescription } }
    private func reparseAndSave() async { let raw = record.rawInput.trimmed; guard !raw.isEmpty else { return }; do { if case .create(var parsed) = try await model.parser.parse(raw) { parsed.id = record.id; parsed.ownerID = record.ownerID; parsed.createdAt = record.createdAt; parsed.important = record.important; lastParsedRaw = raw; save(parsed) } } catch { model.error = "重新解析失败，已保留当前记录。" } }
}

struct RecordForm: View {
    @EnvironmentObject private var model: AppModel; @Binding var record: Record; let showRawInput: Bool; let showsDetailSummary: Bool; let saveTitle: String; let onSave: (Record) -> Void; let onSearch: ((Record) -> Void)?; let onReparse: (() -> Void)?; let onVoice: (() -> Void)?; let onAutoSave: ((Record) -> Void)?; let isRecording: Bool; let voiceLabel: String
    @State private var tags: String; @State private var amount: String; @State private var attachmentMenu = false; @State private var photos = false; @State private var camera = false; @State private var photo: PhotosPickerItem?; @FocusState private var focused: AppFocus?
    init(record: Binding<Record>, showRawInput: Bool, showsDetailSummary: Bool = false, saveTitle: String = "保存", onSave: @escaping (Record) -> Void, onSearch: ((Record) -> Void)? = nil, onReparse: (() -> Void)? = nil, onVoice: (() -> Void)? = nil, onAutoSave: ((Record) -> Void)? = nil, isRecording: Bool = false, voiceLabel: String = "语音补充") { _record = record; self.showRawInput = showRawInput; self.showsDetailSummary = showsDetailSummary; self.saveTitle = saveTitle; self.onSave = onSave; self.onSearch = onSearch; self.onReparse = onReparse; self.onVoice = onVoice; self.onAutoSave = onAutoSave; self.isRecording = isRecording; self.voiceLabel = voiceLabel; _tags = State(initialValue: record.wrappedValue.tags.joined(separator: ", ")); _amount = State(initialValue: record.wrappedValue.amount.map(String.init(describing:)) ?? "") }
    var body: some View { ScrollView { VStack(spacing: 16) { if showsDetailSummary { detailSummary }; card { Picker("模块", selection: $record.module) { ForEach(Module.allCases) { Label($0.title, systemImage: $0.icon).tag($0) } }.pickerStyle(.segmented) }; if showRawInput { card(title: "记录原文", icon: "square.and.pencil", color: .blue, trailing: onReparse == nil ? nil : { focused = nil; onReparse?() }) { TextField("记录原文", text: $record.rawInput, axis: .vertical).focused($focused, equals: .raw).font(.body).lineLimit(3...8).submitLabel(.done).onSubmit { focused = nil; autoSave() } } }; card(title: "内容", icon: "sparkles", color: .purple) { Text(record.content).font(.body).frame(maxWidth: .infinity, alignment: .leading).textSelection(.enabled) }; HStack(alignment: .top, spacing: 12) { card(title: "标签", icon: "tag.fill", color: .purple) { TextField("逗号分隔", text: $tags).focused($focused, equals: .tags).submitLabel(.done).onSubmit { focused = nil } }.frame(maxWidth: .infinity); card(title: "重要", icon: "star.fill", color: .orange) { Toggle("", isOn: $record.important).labelsHidden() }.frame(width: 124).frame(minHeight: 128) }; moduleFields }.padding(.horizontal, 16).padding(.vertical, 18).background(Color.clear.contentShape(Rectangle()).onTapGesture { focused = nil }) }.scrollDismissesKeyboard(.interactively).background(LakeBackground(lightweight: true)).safeAreaInset(edge: .bottom) { if let onVoice { captureBar(onVoice) } }.toolbar { ToolbarItemGroup(placement: .topBarTrailing) { if let onSearch { Button { focused = nil; if let value = prepared() { onSearch(value) } } label: { Label("搜索", systemImage: "magnifyingglass") } }; Button(saveTitle) { focused = nil; if let value = prepared() { onSave(value) } }.buttonStyle(.borderedProminent) }; ToolbarItemGroup(placement: .keyboard) { Spacer(); Button("完成") { focused = nil } } }.confirmationDialog("添加图片", isPresented: $attachmentMenu) { Button("拍照") { if UIImagePickerController.isSourceTypeAvailable(.camera) { camera = true } else { model.error = "当前设备没有可用相机。" } }; Button("从相册选择") { photos = true }; Button("取消", role: .cancel) {} }.photosPicker(isPresented: $photos, selection: $photo, matching: .images).sheet(isPresented: $camera) { CameraPicker() }.onChange(of: record.tags) { tags = $0.joined(separator: ", ") }.onChange(of: record.amount) { amount = $0.map(String.init(describing:)) ?? "" }.onChange(of: focused) { old, new in if old == .raw && new != .raw { autoSave() } }.onChange(of: record.module) { _ in autoSave() }.onChange(of: record.important) { _ in autoSave() }.onChange(of: record.reminderEnabled) { _ in autoSave() }.onChange(of: record.status) { _ in autoSave() }.onChange(of: record.occurredAt) { _ in autoSave() }.onChange(of: record.dueAt) { _ in autoSave() }.onDisappear { focused = nil } }
    private func captureBar(_ onVoice: @escaping () -> Void) -> some View { HStack(spacing: 10) { Button { focused = nil; onVoice() } label: { VStack(spacing: 3) { Image(systemName: isRecording ? "waveform" : "mic.fill").font(.title2); Text(voiceLabel).font(.caption2) }.frame(width: 72, height: 58).foregroundStyle(isRecording ? .white : .blue).background(isRecording ? .blue : .white.opacity(0.85), in: Circle()).shadow(color: .blue.opacity(0.18), radius: 9) }; HStack { TextField("继续说，补充或修改…", text: $record.rawInput).focused($focused, equals: .raw).submitLabel(.search).onSubmit { focused = nil; if let value = prepared() { onSearch?(value) } }; Button { focused = nil; if let value = prepared() { onSearch?(value) } } label: { Image(systemName: "magnifyingglass").font(.title2) } }.padding(.horizontal, 16).frame(height: 58).background(.white.opacity(0.8), in: Capsule()); Button { focused = nil; attachmentMenu = true } label: { Image(systemName: "plus").font(.title2).frame(width: 54, height: 54).background(.white.opacity(0.85), in: Circle()) } }.padding(12).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 30)).padding(.horizontal, 8) }
    private var detailSummary: some View { HStack(spacing: 16) { Image(systemName: record.module.icon).font(.system(size: 34, weight: .semibold)).foregroundStyle(record.module.color).frame(width: 72, height: 72).background(record.module.color.opacity(0.14), in: RoundedRectangle(cornerRadius: 22)); VStack(alignment: .leading, spacing: 5) { Text(record.module.title).font(.headline).foregroundStyle(record.module.color); Text(record.content).font(.title3.bold()).lineLimit(2); Text(record.occurredAt ?? record.createdAt, style: .date).font(.caption).foregroundStyle(.secondary) }; Spacer(); Image(systemName: record.important ? "star.fill" : "star").foregroundStyle(.orange) }.padding(20).frame(maxWidth: .infinity, alignment: .leading).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 30)).overlay(RoundedRectangle(cornerRadius: 30).stroke(.white.opacity(0.95))).shadow(color: record.module.color.opacity(0.16), radius: 18, y: 8) }
    @ViewBuilder private var moduleFields: some View { switch record.module { case .ledger: VStack(spacing: 12) { fieldCard("商家", "storefront.fill", .blue) { optional("商家", $record.merchant, .merchant) }; if record.amountItems.count > 1 { card(title: "金额明细", icon: "banknote.fill", color: .orange) { LazyVGrid(columns: [.init(.flexible()), .init(.flexible())], spacing: 10) { ForEach(record.amountItems, id: \.self) { item in VStack(alignment: .leading) { Text(CurrencyCanonicalizer.displayName(item.currency, languageCode: appLanguageCode) ?? "未标币种").font(.caption).foregroundStyle(.secondary); Text(String(describing: item.value)).font(.title3.bold()) }.frame(maxWidth: .infinity, alignment: .leading).padding(12).background(.white.opacity(0.58), in: RoundedRectangle(cornerRadius: 15)) } } } } else { HStack(alignment: .top, spacing: 12) { fieldCard("金额", "banknote.fill", .orange) { TextField("金额", text: $amount).keyboardType(.decimalPad).focused($focused, equals: .amount) }; fieldCard("货币", "coloncurrencysign.circle.fill", .green) { TextField("币种", text: currencyText).focused($focused, equals: .currency).submitLabel(.done).onSubmit { focused = nil } } } }; HStack(alignment: .top, spacing: 12) { fieldCard("类别", "tag.fill", .purple) { optional("类别", $record.category, .category) }; fieldCard("支付方式", "creditcard.fill", .orange) { optional("支付方式", $record.paymentMethod, .payment) } }; HStack(alignment: .top, spacing: 12) { fieldCard("地点", "mappin.circle.fill", .mint) { optional("地点", $record.location, .location) }.frame(maxWidth: .infinity); fieldCard("日期时间", "calendar", .indigo) { date("日期时间", $record.occurredAt) }.frame(maxWidth: .infinity) } }; case .todo: VStack(spacing: 12) { card(title: "待办时间", icon: "calendar", color: .indigo) { date("日期时间", $record.dueAt) }; HStack { card(title: "提醒", icon: "bell.fill", color: .orange) { Toggle("提醒", isOn: reminderBinding); Text(reminderStatus).font(.caption).foregroundStyle(.secondary) }; card(title: "状态", icon: "checkmark.circle.fill", color: .green) { Picker("状态", selection: Binding(get: { record.status ?? .pending }, set: { record.status = $0 })) { ForEach(TodoStatus.allCases, id: \.self) { Text($0.rawValue).tag($0) } } } }; card(title: "地点", icon: "mappin.circle.fill", color: .mint) { optional("地点", $record.location, .location) } }; case .memo: card(title: "提醒", icon: "bell.fill", color: .orange) { Toggle("提醒", isOn: $record.reminderEnabled) }; case .idea: EmptyView() } }
    private var reminderBinding: Binding<Bool> { Binding(get: { record.reminderState == .requested || record.reminderState == .active }, set: { enabled in record.reminderEnabled = enabled; record.reminderState = enabled ? .requested : .none; if !enabled { record.reminderLinked = false; record.reminderExternalID = nil } }) }
    private var reminderStatus: String { switch record.reminderState { case .none: "未开启"; case .requested: "正在请求系统提醒"; case .active: "系统提醒已建立"; case .permissionDenied: "系统权限已关闭"; case .missingExternalReminder: "系统提醒已被删除" } }
    private func card<Content: View>(title: String? = nil, icon: String? = nil, color: Color = .blue, trailing: (() -> Void)? = nil, @ViewBuilder content: () -> Content) -> some View { VStack(alignment: .leading, spacing: 13) { if let title { HStack { if let icon { Image(systemName: icon).font(.headline).foregroundStyle(color).frame(width: 40, height: 40).background(color.opacity(0.14), in: RoundedRectangle(cornerRadius: 13)) }; Text(title).font(.headline).foregroundStyle(AppTheme.primary); Spacer(); if let trailing { Button(action: trailing) { Image(systemName: "arrow.clockwise").frame(width: 34, height: 34).background(.white.opacity(0.7), in: Circle()) } } } }; content() }.frame(maxWidth: .infinity, alignment: .leading).padding(17).background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 26)).background(LinearGradient(colors: [.white.opacity(0.72), color.opacity(0.055)], startPoint: .topLeading, endPoint: .bottomTrailing), in: RoundedRectangle(cornerRadius: 26)).overlay(RoundedRectangle(cornerRadius: 26).stroke(.white.opacity(0.95), lineWidth: 1.2)).shadow(color: color.opacity(0.14), radius: 14, y: 7) }
    private func fieldCard<Content: View>(_ title: String, _ icon: String, _ color: Color, @ViewBuilder content: () -> Content) -> some View { card(title: title, icon: icon, color: color) { content() }.frame(minHeight: 112, alignment: .top) }
    private func optional(_ title: String, _ value: Binding<String?>, _ field: AppFocus) -> some View { TextField(title, text: Binding(get: { value.wrappedValue ?? "" }, set: { value.wrappedValue = $0.isEmpty ? nil : $0 })).focused($focused, equals: field).submitLabel(.done).onSubmit { focused = nil } }
    private var currencyText: Binding<String> { Binding(get: { CurrencyCanonicalizer.displayName(record.currency, languageCode: appLanguageCode) ?? "" }, set: { record.currency = CurrencyCanonicalizer.canonical($0) }) }
    private func date(_ title: String, _ value: Binding<Date?>) -> some View { VStack(alignment: .leading) { Toggle("设置", isOn: Binding(get: { value.wrappedValue != nil }, set: { value.wrappedValue = $0 ? Date() : nil })); if value.wrappedValue != nil { DatePicker(title, selection: Binding(get: { value.wrappedValue! }, set: { value.wrappedValue = $0 }), displayedComponents: [.date, .hourAndMinute]).labelsHidden() } } }
    private func autoSave() { guard onAutoSave != nil, let value = prepared() else { return }; onAutoSave?(value) }
    private func prepared() -> Record? { focused = nil; var value = record; value.tags = tags.csv; value.currency = CurrencyCanonicalizer.canonical(value.currency); guard amount.isEmpty || Decimal(string: amount) != nil else { model.error = "金额格式无效"; return nil }; if value.module == .ledger, value.amountItems.count <= 1 { value.amount = amount.isEmpty ? nil : Decimal(string: amount); value.amountItems = value.amount.map { [AmountItem(value: $0, currency: value.currency)] } ?? [] }; record = value; return value }
}

struct RecordRow: View { let record: Record; var body: some View { VStack(alignment: .leading) { Text(record.content).lineLimit(2); Text(record.occurredAt ?? record.createdAt, style: .date).font(.caption).foregroundStyle(.secondary) } } }

struct CameraPicker: UIViewControllerRepresentable {
    @Environment(\.dismiss) private var dismiss
    func makeCoordinator() -> Coordinator { Coordinator(dismiss: dismiss) }
    func makeUIViewController(context: Context) -> UIImagePickerController { let picker = UIImagePickerController(); picker.sourceType = .camera; picker.delegate = context.coordinator; return picker }
    func updateUIViewController(_ uiViewController: UIImagePickerController, context: Context) {}
    final class Coordinator: NSObject, UIImagePickerControllerDelegate, UINavigationControllerDelegate { let dismiss: DismissAction; init(dismiss: DismissAction) { self.dismiss = dismiss }; func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any]) { dismiss() }; func imagePickerControllerDidCancel(_ picker: UIImagePickerController) { dismiss() } }
}

@MainActor final class SpeechInput: ObservableObject {
    enum Phase { case idle, listening, processing }
    @Published var transcript = ""; @Published var finishedTranscript: String?; @Published var phase: Phase = .idle; @Published var error: String?
    var isRecording: Bool { phase == .listening }; var statusText: String { phase == .listening ? "正在听…" : phase == .processing ? "正在识别…" : "语音补充" }
    let primaryLocale = Locale(identifier: "zh-CN")
    let secondaryLocale = Locale(identifier: "en-US")
    private let engine = AVAudioEngine(); private var task: SFSpeechRecognitionTask?; private var request: SFSpeechAudioBufferRecognitionRequest?; private var tapInstalled = false
    func start() { SFSpeechRecognizer.requestAuthorization { [weak self] status in Task { @MainActor in guard status == .authorized else { self?.error = "请允许语音识别权限。"; return }; AVAudioApplication.requestRecordPermission { allowed in Task { @MainActor in guard allowed else { self?.error = "请允许麦克风权限。"; return }; self?.begin() } } } } }
    private func begin() { tearDown(); transcript = ""; finishedTranscript = nil; guard let recognizer = SFSpeechRecognizer(locale: primaryLocale), recognizer.isAvailable else { error = "系统语音识别不可用。"; return }; let request = SFSpeechAudioBufferRecognitionRequest(); request.shouldReportPartialResults = true; request.contextualStrings = ["沃尔玛", "Target", "Costco", "Amazon", "Visa", "Starbucks", "iPhone"]; self.request = request; let node = engine.inputNode; node.installTap(onBus: 0, bufferSize: 1024, format: node.outputFormat(forBus: 0)) { buffer, _ in request.append(buffer) }; tapInstalled = true; task = recognizer.recognitionTask(with: request) { [weak self] result, failure in Task { @MainActor in guard let self else { return }; if let result { self.transcript = result.bestTranscription.formattedString }; if failure != nil || result?.isFinal == true { self.finish() } } }; do { try AVAudioSession.sharedInstance().setCategory(.record, mode: .measurement); try AVAudioSession.sharedInstance().setActive(true); engine.prepare(); try engine.start(); phase = .listening } catch { tearDown(); self.error = "无法启动麦克风：\(error.localizedDescription)" } }
    private func finish() { guard request != nil || task != nil else { return }; phase = .processing; let finalText = transcript; tearDown(); if !finalText.trimmed.isEmpty { finishedTranscript = finalText }; phase = .idle }
    func stop() { guard phase != .idle else { return }; finish() }
    private func tearDown() { if engine.isRunning { engine.stop() }; if tapInstalled { engine.inputNode.removeTap(onBus: 0); tapInstalled = false }; request?.endAudio(); task?.cancel(); request = nil; task = nil }
}

private extension String { var trimmed: String { trimmingCharacters(in: .whitespacesAndNewlines) }; var csv: [String] { split(separator: ",").map { String($0).trimmed }.filter { !$0.isEmpty } } }
@MainActor private extension Module { var icon: String { switch self { case .ledger: "chart.bar.fill"; case .todo: "checkmark.square.fill"; case .memo: "note.text"; case .idea: "lightbulb.fill" } }; var decoration: String { switch self { case .ledger: "creditcard.fill"; case .todo: "checklist"; case .memo: "note.text"; case .idea: "sparkles" } }; var subtitle: String { switch self { case .ledger: "轻松记账，清楚每一笔"; case .todo: "记下任务，安心完成"; case .memo: "随手记录，整理生活"; case .idea: "闪现的想法，值得记录" } }; var color: Color { switch self { case .ledger: AppTheme.ledgerAccent; case .todo: AppTheme.todoAccent; case .memo: AppTheme.memoAccent; case .idea: AppTheme.ideaAccent } } }
